### ISSUE TITLE
Add public "from" method to Image trait

### ISSUE THREAD

**Issue by brmmm3** [MoAlyousef/fltk-rs#100]
Currently I'm missing an option to create images from embedded data.
There is a crate called `rust-embed`, which let's you easily embed external data, like images into the Rust code. The `get` method in that crate returns a `Cow<'static, [u8]>`.
It would be great to be able to code something like:

`let img = PngImage::from(embedded_data.get('app.png'));`

**Comment by MoAlyousef** [comment]
I've added a ```from_data(data: &[u8])``` method to the respective Image structs. It's currently in master.

```rust
#[derive(RustEmbed)]
#[folder = "examples/"]
struct Asset;
let img = Asset::get("image.jpg").unwrap();
let jpg = fltk::image::JpegImage::from_data(&img);
```
