### ISSUE TITLE
[BUG] Build fails with toolchain msvc

### ISSUE THREAD

**Issue by brmmm3** [MoAlyousef/fltk-rs#128]
I'm using nightly-msvc on Windows with fltk 0.5.0. cargo build fails with the following error message:
error: failed to run custom build command for `fltk-sys v0.5.0`

Caused by:
  process didn't exit successfully: `C:\Workspace\Rust\FastTools\target\debug\build\fltk-sys-c2b887145bc803c1\build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=build.rs
cargo:rerun-if-changed=cfltk/cfl.h
cargo:rerun-if-changed=cfltk/cfl_widget.h
cargo:rerun-if-changed=cfltk/cfl_group.h
cargo:rerun-if-changed=cfltk/cfl_window.h
cargo:rerun-if-changed=cfltk/cfl_button.h
cargo:rerun-if-changed=cfltk/cfl_box.h
cargo:rerun-if-changed=cfltk/cfl_menu.h
cargo:rerun-if-changed=cfltk/cfl_dialog.h
cargo:rerun-if-changed=cfltk/cfl_valuator.h
cargo:rerun-if-changed=cfltk/cfl_browser.h
cargo:rerun-if-changed=cfltk/cfl_misc.h
cargo:rerun-if-changed=cfltk/cfl_text.h
cargo:rerun-if-changed=cfltk/cfl_image.h
cargo:rerun-if-changed=cfltk/cfl_draw.h
cargo:rerun-if-changed=cfltk/cfl_table.h
cargo:rerun-if-changed=cfltk/cfl.cpp
cargo:rerun-if-changed=cfltk/cfl_widget.cpp
cargo:rerun-if-changed=cfltk/cfl_group.cpp
cargo:rerun-if-changed=cfltk/cfl_window.cpp
cargo:rerun-if-changed=cfltk/cfl_button.cpp
cargo:rerun-if-changed=cfltk/cfl_box.cpp
cargo:rerun-if-changed=cfltk/cfl_menu.cpp
cargo:rerun-if-changed=cfltk/cfl_dialog.cpp
cargo:rerun-if-changed=cfltk/cfl_valuator.cpp
cargo:rerun-if-changed=cfltk/cfl_browser.cpp
cargo:rerun-if-changed=cfltk/cfl_misc.cpp
cargo:rerun-if-changed=cfltk/cfl_text.cpp
cargo:rerun-if-changed=cfltk/cfl_image.cpp
cargo:rerun-if-changed=cfltk/cfl_draw.cpp
cargo:rerun-if-changed=cfltk/cfl_table.cpp
cargo:rerun-if-changed=cfltk/cfl_tree.cpp
cargo:rerun-if-changed=cfltk/CMakeLists.txt
running: "cmake" "C:\\Users\\bam5wi\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\fltk-sys-0.5.0\\cfltk" "-G" "Visual Studio 14 2015" "-Thost=x64" "-Ax64" "-DOPTION_USE_SYSTEM_LIBPNG=OFF" "-DOPTION_USE_SYSTEM_LIBJPEG=OFF" "-DOPTION_USE_SYSTEM_ZLIB=OFF" "-DOpenGL_GL_PREFERENCE=GLVND" "-DOPTION_ABI_VERSION:STRING=10401" "-DOPTION_BUILD_EXAMPLES=OFF" "-DOPTION_USE_THREADS=ON" "-DOPTION_LARGE_FILE=ON" "-DOPTION_BUILD_HTML_DOCUMENTATION=OFF" "-DOPTION_BUILD_PDF_DOCUMENTATION=OFF" "-DCMAKE_INSTALL_PREFIX=C:\\Workspace\\Rust\\FastTools\\target\\debug\\build\\fltk-sys-2a714bbae49aa2b6\\out" "-DCMAKE_C_FLAGS= -nologo -MD -Brepro" "-DCMAKE_C_FLAGS_RELEASE= -nologo -MD -Brepro" "-DCMAKE_CXX_FLAGS= -nologo -MD -Brepro" "-DCMAKE_CXX_FLAGS_RELEASE= -nologo -MD -Brepro" "-DCMAKE_ASM_FLAGS= -nologo -MD -Brepro" "-DCMAKE_ASM_FLAGS_RELEASE= -nologo -MD -Brepro" "-DCMAKE_BUILD_TYPE=RELEASE"
-- Selecting Windows SDK version 10.0.10586.0 to target Windows 10.0.17763.
-- Warning: Header file GL/glu.h was not found.
-- The FLTK team recommends to rerun CMake from a
-- "Developer Command Prompt for Visual Studio xxxx"
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Workspace/Rust/FastTools/target/debug/build/fltk-sys-2a714bbae49aa2b6/out/build
running: "cmake" "--build" "." "--target" "install" "--config" "RELEASE" "--"
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.

  cfl_window.cpp
C:\Users\bam5wi\.cargo\registry\src\github.com-1ecc6299db9ec823\fltk-sys-0.5.0\cfltk\cfl_window.cpp(42): error C2059: syntax error: 'type' [C:\Workspace\Rust\FastTools\target\debug\build\fltk-sys-2a714bbae49aa2b6\out\build\cfltk.vcxproj]
C:\Users\bam5wi\.cargo\registry\src\github.com-1ecc6299db9ec823\fltk-sys-0.5.0\cfltk\cfl_window.cpp(48): error C2059: syntax error: 'type' [C:\Workspace\Rust\FastTools\target\debug\build\fltk-sys-2a714bbae49aa2b6\out\build\cfltk.vcxproj]
C:\Users\bam5wi\.cargo\registry\src\github.com-1ecc6299db9ec823\fltk-sys-0.5.0\cfltk\cfl_window.cpp(54): error C2059: syntax error: 'type' [C:\Workspace\Rust\FastTools\target\debug\build\fltk-sys-2a714bbae49aa2b6\out\build\cfltk.vcxproj]
C:\Users\bam5wi\.cargo\registry\src\github.com-1ecc6299db9ec823\fltk-sys-0.5.0\cfltk\cfl_window.cpp(60): error C2059: syntax error: 'type' [C:\Workspace\Rust\FastTools\target\debug\build\fltk-sys-2a714bbae49aa2b6\out\build\cfltk.vcxproj]
  cfl_button.cpp
...
C:\Users\bam5wi\.cargo\registry\src\github.com-1ecc6299db9ec823\fltk-sys-0.5.0\cfltk\cfl_tree.cpp(10): error C2059: syntax error: 'type' [C:\Workspace\Rust\FastTools\target\debug\build\fltk-sys-2a714bbae49aa2b6\out\build\cfltk.vcxproj]
  Generating Code...
  fltk.vcxproj -> C:\Workspace\Rust\FastTools\target\debug\build\fltk-sys-2a714bbae49aa2b6\out\lib\Release\fltk.lib
  fltk_forms.vcxproj -> C:\Workspace\Rust\FastTools\target\debug\build\fltk-sys-2a714bbae49aa2b6\out\lib\Release\fltk_forms.lib
  fltk_gl.vcxproj -> C:\Workspace\Rust\FastTools\target\debug\build\fltk-sys-2a714bbae49aa2b6\out\lib\Release\fltk_gl.lib
  fltk_jpeg.vcxproj -> C:\Workspace\Rust\FastTools\target\debug\build\fltk-sys-2a714bbae49aa2b6\out\lib\Release\fltk_jpeg.lib
  fltk_z.vcxproj -> C:\Workspace\Rust\FastTools\target\debug\build\fltk-sys-2a714bbae49aa2b6\out\lib\Release\fltk_z.lib
  fltk_png.vcxproj -> C:\Workspace\Rust\FastTools\target\debug\build\fltk-sys-2a714bbae49aa2b6\out\lib\Release\fltk_png.lib
  fltk_images.vcxproj -> C:\Workspace\Rust\FastTools\target\debug\build\fltk-sys-2a714bbae49aa2b6\out\lib\Release\fltk_images.lib
  fluid.vcxproj -> C:\Workspace\Rust\FastTools\target\debug\build\fltk-sys-2a714bbae49aa2b6\out\build\fltk\bin\Release\fluid.exe

--- stderr
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
thread 'main' panicked at '
command did not execute successfully, got: exit code: 1

With toolchain nightly-gnu cargo build runs fine.

**Comment by MoAlyousef** [comment]
Hi
The MSVC toolchain you're using is quite old. Microsoft is known to break abi between versions. And there are versions 2017 and now 2019. Also this release requires C++17 for certain features which are basically impossible without. The build is also not finding some system GL headers, so it's recommended to build from the native tools command prompt. (It should appear once you start typing "native" in the start menu)

**Comment by MoAlyousef** [comment]
Anyway, I have reverted the C++17 change. Can you try building from the master branch?

**Comment by brmmm3** [comment]
Thanks! Master compiles again.
