### ISSUE TITLE
Table example

### ISSUE THREAD

**Issue by JesperAxelsson** [MoAlyousef/fltk-rs#174]
Hi!
I want to start of by saying how easy it was to get up and running with this project! 
Searching the examples I could not find out how to setup a Table with data. I tried the using the custom widget example to override draw_cells but the `TableContext` seems to be missing. (Or I just couldn't find it)

Setting up an example like [table-simple](https://github.com/fltk/fltk/blob/master/examples/table-simple.cxx) might be helpful both for me and for other user.

**Comment by MoAlyousef** [comment]
Hello
You're right. TableContext and draw_cell were missing, I've just added them, and added a table.rs example which is basically a simplified translation of the C++ example. 
https://github.com/MoAlyousef/fltk-rs/blob/master/examples/table.rs

The changes are currently in master. I'll publish a newer version after the CI tests pass.

**Comment by JesperAxelsson** [comment]
Sweet, thank you!
