### ISSUE TITLE
Missing Methods in Fl_browser

### ISSUE THREAD

**Issue by milustreamer** [MoAlyousef/fltk-rs#194]
I find the fltk wrapper very interesting.
When reproducing the C ++ example for fltk from "Erco's FLTK Cheat Page" "Using FL_Browser with columns" I have the problem that the methods "column_widths", "column_char" are not implemented.
Can these methods be implemented in fltk-rs with little effort?
Thank you

**Comment by MoAlyousef** [comment]
Hi
Yes they should be straight forward to implement. I’ll check them out this evening.

**Comment by milustreamer** [comment]
Hi,
thank you for the kindly answer

**Comment by MoAlyousef** [comment]
No problem.
I've pushed the missing Fl_Browser methods, and have added an example (basically a translation of Erco's example) here:
https://github.com/MoAlyousef/fltk-rs/blob/master/examples/browser.rs

I'm still waiting for the CI, I'll also take another look this evening to check if all's ok, then publish a new patch.

**Comment by milustreamer** [comment]
Thank You very match for the quick fix.
I have test it ok and close the case.
