### ISSUE TITLE
Is there a way to "get" the windows dimensions when it has been resized  ?

### ISSUE THREAD

**Issue by serge-hulne** [MoAlyousef/fltk-rs#197]
If yes, is there also a way to detect the (end of) a resizing event (to automatically detect the new dimensions after a window resizing ebent)?

That could be a useful feature, for instance to resize the fonts along with the widows (since by default the font do not scale up along with the widgets).

**Comment by MoAlyousef** [comment]
Unfortunately FLTK doesn't have a resize event. The only solution in my mind is to tap into the window's size in the event loop, something like the following:
```rust
use fltk::*;

fn main() {
    let app = app::App::default();
    let mut win = window::Window::new(200, 200, 400, 300, "");
    let mut frame = frame::Frame::new(0, 0, 400, 300, "Hello");
    win.make_resizable(true);
    win.end();
    win.show();

    while app.wait().unwrap() {
        frame.set_label_size(frame.width()/25);
    }
}
```

**Comment by serge-hulne** [comment]
Thank you very much!

**Comment by MoAlyousef** [comment]
You're welcome
