### ISSUE TITLE
[BUG]"Cannot find type <Message> in this scope" when trying ot snippet about events handlling (from fltk-rs doc)

### ISSUE THREAD

**Issue by serge-hulne** [MoAlyousef/fltk-rs#198]
Hi! I tried the following snippet from the doc about fltk-rs:

`    /* previous counter code */
    let (s, r) = app::channel::<Message>();

    but_inc.emit(s, Message::Increment);
    but_dec.emit(s, Message::Decrement);
    
    while app.wait().unwrap() {
        let label: i32 = frame.label().parse().unwrap();
        match r.recv() {
            Some(Message::Increment) => frame.set_label(&(label + 1).to_string()),
            Some(Message::Decrement) => frame.set_label(&(label - 1).to_string()),
            None => (),
        }
    }`

More precisely, I replaced :
`app.run().unwrap(); `
in the counter example with the snippet above, but

but I get the error message: "Cannot find type <Message> in this scope".

I'm using:
- Rust 1.44.1
- fltk-rs from crates.io : fltk = "0.7.4"

**Comment by MoAlyousef** [comment]
Hi
The snippet lacks the definition of message for brevity. You can try the full example here:
https://github.com/MoAlyousef/fltk-rs/blob/master/examples/counter2.rs

**Comment by serge-hulne** [comment]
Thank you!
