### ISSUE TITLE
Hi, is there an option to pack widgets horizontally in fltk-rs?

### ISSUE THREAD

**Issue by serge-hulne** [MoAlyousef/fltk-rs#210]
Hi, is there an option to pack widgets horizontally in fltk-rs?

I seem to remember that the "pack" container in the original fltk in C++ had an option to this end:

Serge.

`
use fltk::{app::*, button::*, window::*, group::*, input::*};

fn main() {
    let app = App::default();
    let mut wind = Window::new(100, 100, 400, 300, "Hello from rust");

    // Group 1
    // #######
    let e1 = Input::new(0, 0, 80, 40, "");
    let mut  b1 = Button::new(0, 0, 80, 40, "Button 1");
    let mut  b2 = Button::new(0, 0, 80, 40, "Button 2");

    let mut p = Pack::new(50, 50, 300, 100, "");
    //Packing group 1
    p.add(&e1);
    p.add(&b1);
    p.add(&b2);
    p.set_spacing(5);
    p.end();

    wind.end();
    wind.show();
    app.run().unwrap();
}

`

**Comment by MoAlyousef** [comment]
Hi

Yes you can use the PackType::Horizontal

p.set_type(PackType::Horizontal);

**Comment by serge-hulne** [comment]
Fantastic!
Thank you.
