### ISSUE TITLE
Is there any way to call drop on the boxed closures passed to handle, draw_cell, etc?

### ISSUE THREAD

**Issue by estokes** [MoAlyousef/fltk-rs#219]
Nice binding, fltk is refreshingly simple! I've got a very dynamic and potentially long lived application, lots of widgets changing, and lots of state needing to be wrapped by the Box<Fn ...> closures and passed to handle, draw_cell, etc. When a window is closed it would be really nice to be able to get these closures back so they can be dropped properly, the current work around is to capture only weak references, but that's really not ideal.

**Comment by MoAlyousef** [comment]
Hi
Thank you
There are a few unsafe WidgetExt methods which reclaim the boxed closures, namely user_data(&self) and draw_data(&self). 
You can also call WidgetExt::unsafe_delete or GroupExt::unsafe_clear which will delete captured data. There are safe variants which leak the user_data, and I can’t think of a way at the moment of ensuring safety, other than restructuring the program to use messages and handle events in the event loop, which does no captures.
