### ISSUE TITLE
Unable to use set_icon with newer versions

### ISSUE THREAD

**Issue by brmmm3** [MoAlyousef/fltk-rs#220]
In older versions, like 0.6, it was possible to set the window icon with:

`wnd.set_icon(&PngImage::from_data(&icon).unwrap());`

But now I get the error message:

expected enum `std::option::Option`, found `&fltk::image::PngImage`
help: try using a variant of the expected enum: `Some(&PngImage::from_data(&icon).unwrap())`

When I try to set the icon with:

`wnd.set_icon(Some(&PngImage::from_data(&icon).unwrap()));`

I get the error message:

the trait `fltk::ImageExt` is not implemented for `&fltk::image::PngImage`

**Comment by MoAlyousef** [comment]
Hi
This was changed to be able to unset an icon using the same method. 
You would have to use:
```rust
wnd.set_icon(Some(PngImage::from_data(&icon).unwrap)); // without the &
```
