### ISSUE TITLE
[BUG] Error building on pop os (ubuntu derivative)

### ISSUE THREAD

**Issue by jlgerber** [MoAlyousef/fltk-rs#222]
**Describe the bug**
Following the tutorial, I install the devel dependencies as outlined in the docs. I then  add the fltk dependency in cargo with the fltk-bundled feature, build a basic hello world app straight from the example, then attempt to ```cargo run```. I get 

```Compiling fltk v0.7.12
error: could not find native static library `cfltk`, perhaps an -L flag is missing?

error: aborting due to previous error

error: could not compile `fltk-sys`.
``` 

**To Reproduce**
At least on pop-os
1. install devel deps
2. run ```cargo new fltktest```
3. add ```fltk = {version="^0.7.12", features = ["fltk-bundled"]}``` to dependencies in Cargo.toml
4 . add the following to main.rs
```
use fltk::{app::*, button::*, frame::*, window::*};
fn main() { 
    let app = App::default();
    let mut wind = Window::new(100,100,400,300, "Hello from Rust");
    let mut frame = Frame::new(0, 0, 400,200, "");
    let mut btn = Button::new(160, 210, 80, 40, "Click Me!");
    wind.end();
    wind.show();
    btn.set_callback(Box::new(move || frame.set_label("Hello World")));
    app.run().unwrap();
}
```
5. run ```cargo run```

**Expected behavior**
build and get an flltk window

**Desktop (please complete the following information):**
- Linux pop-os 5.4.0-7634-generic #38~1592497129~20.04~9a1ea2e-Ubuntu SMP Fri Jun 19 22:43:37 UTC  x86_64 x86_64 x86_64 GNU/Linux

**Comment by MoAlyousef** [comment]
Hi 
Can you try without the fltk-bundled flag?
You’ll need cmake and a C++ compiler.
