### ISSUE TITLE
[BUG] Support visual studio 2013

### ISSUE THREAD

**Issue by lynnux** [MoAlyousef/fltk-rs#223]
I'm using msvc 2013, it's failed to build fltk-sys, I open `target\release\build\fltk-sys-69cf4b771d9caeb3\out\build\cfltk.sln` to manully build, it shows in cfltk/cfl.cpp:
```
unsigned int Fl_rand(void) {
    std::mt19937 rng;
    std::uniform_int_distribution<std::mt19937::result_type> dist(0, UINT_FAST32_MAX);
    rng.seed(std::random_device()());
    return dist(rng);
}
```
msvc2013 don't have UINT_FAST32_MAX, and I add `#define UINT_FAST32_MAX (4294967295UL)`, then it compile successful.

**Comment by MoAlyousef** [comment]
Since I don’t have msvc 2013, can you check if it’s just a missing header stdint.h?
Try adding it to the top of the file cfl.cpp. 
The define should be available since C++11 (2011).

**Comment by lynnux** [comment]
@MoAlyousef , you are right!   Add `#include <stdint.h>` works, so please include this in next release, thanks!

**Comment by MoAlyousef** [comment]
Sure, will be in the next release today.

**Comment by lynnux** [comment]
Hi, in 0.10.2 version, there are two place need to change to support 2013:
1.https://github.com/MoAlyousef/fltk-rs/blob/master/fltk-sys/cfltk/src/cfl.cpp#L439[
](https://github.com/MoAlyousef/fltk-rs/blob/master/fltk-sys/cfltk/src/cfl.cpp#L439) `snprintf(str, length + 1, "%s", info);`
2. https://github.com/MoAlyousef/fltk-rs/blob/master/fltk-sys/cfltk/src/cfl_new.cpp#L11`void operator delete(void *val) noexcept`, 2013 don't support `noexcept`, also [https://github.com/MoAlyousef/fltk-rs/blob/master/fltk-sys/cfltk/src/cfl_new.cpp#L15](https://github.com/MoAlyousef/fltk-rs/blob/master/fltk-sys/cfltk/src/cfl_new.cpp#L15)
I changed `snprintf` to `_snprintf` and delete `noexcept`, then compiled successful.

**Comment by MoAlyousef** [comment]
Hi
I've pushed a change just now to support msvc 2013 and lower. 
It consists of ifdefs basically.
Can you try building with the master branch since I can't test it?

**Comment by lynnux** [comment]
Thank you @MoAlyousef , it works!
