### ISSUE TITLE
Prebuild binaries on macOS 10.14 instead of 10.15

### ISSUE THREAD

**Issue by LoganDark** [MoAlyousef/fltk-rs#228]
Many people choose to stay on 10.14 due to 32-bit support and, to be honest, Catalina's straight-up _unattractiveness_. Since you seem to specify the version of macOS in your workflow yml thing, wouldn't it be possible to specify 10.14 instead of 10.15?

I believe this has no drawbacks, only benefits. Since `fltk-rs` already compiles and runs on my 10.14 system when not using the bundled libraries, it's silly to prebuild the binaries on a later version because that does absolutely nothing but _restrict_ the operating systems these apps can run on.

As far as I can tell, you don't use Swift UI or any other features that require Catalina. Specifying 10.15 just because it's "the bestest version" isn't very nice :P

Ideally you would specify the very lowest version of the operating system that this library functions on, rather than the newest version just because you can.

**Comment by MoAlyousef** [comment]
Unfortunately Github Actions dropped macos 10.14 support. 
https://github.blog/changelog/2019-10-31-github-actions-macos-virtual-environment-is-updating-to-catalina-and-dropping-mojave-support/

**Comment by LoganDark** [comment]
Oh, wow. I did not know about that.

That's honestly disgusting. They're making the choice for every single library on GitHub that uses that environment, even though some have reasons not to (like _not simply upgrading the version because it's "newer"_). They could have kept the older version, but didn't.

If I had a repository where this were used, I would have immediately moved somewhere else because that is unacceptable. I do **not** support Catalina or anyone who thinks dropping support for all lower versions is _necessary_.

---

Rant aside, feel free to close this issue if you feel that it would be too hard to support 10.14 (like setting up another CI server or using an existing solution for FOSS projects).

**Comment by MoAlyousef** [comment]
I’ll keep the issue open for now since I’m anticipating similar issues when the new arm macbooks are released.
