### ISSUE TITLE
[BUG] Build fails on armv7 targets

### ISSUE THREAD

**Issue by Zalasus** [MoAlyousef/fltk-rs#252]
**Describe the bug**
Trying to compile this on a Raspberry Pi Model 3B running Raspbian causes a compile error in the expansion of the WindowExt derive macro. The same error occurs when cross-compiling from my AMD64 desktop running Debian Buster using the *armv7-unknown-linux-gnueabihf* target. On both platforms, the stable branch of Rust was used.

**Compiler output**
This error appears in every location where WindowExt is derived:
```
error[E0308]: mismatched types
  --> src/window.rs:34:31
   |
34 | #[derive(WidgetExt, GroupExt, WindowExt, Debug)]
   |                               ^^^^^^^^^
   |                               |
   |                               expected `u64`, found `u32`
   |                               expected `u64` because of return type
   |                               help: you can convert an `u32` to `u64`: `WindowExt.into()`
   |
   = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by Zalasus** [comment]
It seems like this bug was caused by a different data model on that architecture concerning the `long` type. By simply adding an explicit cast to the `raw_handle()` implementation, I could get the library to compile and run. I've made a pull request.

**Comment by MoAlyousef** [comment]
Indeed. I haven't taken that into account. I've merged the pull request, and will be publishing a patch tonight.
Thank you.

**Comment by Zalasus** [comment]
Glad I could help. Thank you for maintaining this library, so far it works great for me :)
