### ISSUE TITLE
How can I update the interface periodically?

### ISSUE THREAD

**Issue by super119** [MoAlyousef/fltk-rs#254]
Say if I'd like to update the main window and all widgets in it every 2 seconds, how can I do that?
I tried to use "while app.wait().unwrap { ... }", but it seems that "app.wait()" blocks until there are events(mouse moving, clicking and etc.), so it doesn't meet my requirement...

**Comment by MoAlyousef** [comment]
Hi
I think it should work with add_timeout and repeat_timeout methods.
This is a modification of the timeout example:

```rust
use fltk::*;

fn callback(app: app::App) {
    app.redraw();
    // println!("TICK");
    app::repeat_timeout(2.0, Box::new(move || {
        callback(app);
    }));
}

fn main() {
    let app = app::App::default();
    let mut wind = window::Window::new(100, 100, 400, 300, "");
    wind.show();

    app::add_timeout(2.0, Box::new(move || {
        callback(app);
    }));

    app.run().unwrap();
}
```

**Comment by MoAlyousef** [comment]
I'll also push an update tonight which makes the app::redraw() free function available. So the code can become:
```rust
use fltk::*;

fn callback() {
    app::redraw();
    app::repeat_timeout(2.0, Box::new(callback));
}

fn main() {
    let app = app::App::default();
    let mut wind = window::Window::new(100, 100, 400, 300, "");
    wind.show();

    app::add_timeout(2.0, Box::new(callback));

    app.run().unwrap();
}
```

**Comment by super119** [comment]
Awesome, thanks MoAlyousef, I'll give this a try.

**Comment by MoAlyousef** [comment]
You’re welcome :)
