### ISSUE TITLE
Support build target x86_64-unknown-linux-musl

### ISSUE THREAD

**Issue by oyundev** [MoAlyousef/fltk-rs#263]
I'm trying to build hello world example on Ubuntu 18.04. Cargo run works fine but sadly it's failing when I target x86_64-unknown-linux-musl:
---
[dependencies]
fltk = { version = "^0.8", features = ["fltk-bundled"] }
 
use fltk::{app::*, window::*};

fn main() {
    let app = App::default();
    let mut wind = Window::new(100, 100, 400, 300, "Hello from rust");
    wind.end();
    wind.show();
    app.run().unwrap();
}
---
$ cargo build --target x86_64-unknown-linux-musl --release
   Compiling proc-macro2 v1.0.19
   Compiling unicode-xid v0.2.1
   Compiling cc v1.0.58
   Compiling libc v0.2.74
   Compiling syn v1.0.38
   Compiling cmake v0.1.44
   Compiling quote v1.0.7
   Compiling fltk-sys v0.8.0
   Compiling fltk-derive v0.8.0
   Compiling fltk v0.8.0
   Compiling fltk-rs v0.1.0 (/home/user1/code/fltk-rs)
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-Wl,--eh-frame-hdr" "-m64" "-nostartfiles" "/home/user1/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-musl/lib/crt1.o" "/home/user1/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-musl/lib/crti.o" "-L" "/home/user1/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-musl/lib" "/home/user1/code/fltk-rs/target/x86_64-unknown-linux-musl/release/deps/fltk_rs-761d3fb72fa651b5.fltk_rs.bvefhfop-cgu.0.rcgu.o" "/home/user1/code/fltk-rs/target/x86_64-unknown-linux-musl/release/deps/fltk_rs-761d3fb72fa651b5.fltk_rs.bvefhfop-cgu.1.rcgu.o" "/home/user1/code/fltk-rs/target/x86_64-unknown-linux-musl/release/deps/fltk_rs-761d3fb72fa651b5.fltk_rs.bvefhfop-cgu.2.rcgu.o" "/home/user1/code/fltk-rs/target/x86_64-unknown-linux-musl/release/deps/fltk_rs-761d3fb72fa651b5.fltk_rs.bvefhfop-cgu.3.rcgu.o" "/home/user1/code/fltk-rs/target/x86_64-unknown-linux-musl/release/deps/fltk_rs-761d3fb72fa651b5.fltk_rs.bvefhfop-cgu.4.rcgu.o" "-o" "/home/user1/code/fltk-rs/target/x86_64-unknown-linux-musl/release/deps/fltk_rs-761d3fb72fa651b5" "/home/user1/code/fltk-rs/target/x86_64-unknown-linux-musl/release/deps/fltk_rs-761d3fb72fa651b5.3xo2i159w246872j.rcgu.o" "-Wl,--gc-sections" "-static" "-no-pie" "-Wl,-zrelro" "-Wl,-znow" "-Wl,-O1" "-nodefaultlibs" "-L" "/home/user1/code/fltk-rs/target/x86_64-unknown-linux-musl/release/deps" "-L" "/home/user1/code/fltk-rs/target/release/deps" "-L" "/home/user1/code/fltk-rs/target/x86_64-unknown-linux-musl/release/build/fltk-sys-3385d078ac279d7c/out/build" "-L" "/home/user1/code/fltk-rs/target/x86_64-unknown-linux-musl/release/build/fltk-sys-3385d078ac279d7c/out/lib" "-L" "/home/user1/code/fltk-rs/target/x86_64-unknown-linux-musl/release/build/fltk-sys-3385d078ac279d7c/out/lib/Release" "-L" "/home/user1/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-musl/lib" "-Wl,-Bstatic" "/home/user1/code/fltk-rs/target/x86_64-unknown-linux-musl/release/deps/libfltk-675c4c47faf840ae.rlib" "/home/user1/code/fltk-rs/target/x86_64-unknown-linux-musl/release/deps/libfltk_sys-67e52d1c92b52bcd.rlib" "/home/user1/code/fltk-rs/target/x86_64-unknown-linux-musl/release/deps/liblibc-5a350c1324af1eb5.rlib" "-Wl,--start-group" "/home/user1/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-musl/lib/libstd-4c028497f01d89c4.rlib" "/home/user1/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-musl/lib/libpanic_unwind-7de66f052926939b.rlib" "/home/user1/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-musl/lib/libhashbrown-d2650d6f5cc1438b.rlib" "/home/user1/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-musl/lib/librustc_std_workspace_alloc-1eb1677cc3169645.rlib" "/home/user1/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-musl/lib/libbacktrace-0ecab0fea5a59771.rlib" "/home/user1/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-musl/lib/libbacktrace_sys-77a1d6b6dd0107fe.rlib" "/home/user1/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-musl/lib/librustc_demangle-de6614b4b7a7a829.rlib" "/home/user1/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-musl/lib/libunwind-1086d1c1e93d9013.rlib" "/home/user1/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-musl/lib/libcfg_if-e75106bd58a0f076.rlib" "/home/user1/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-musl/lib/liblibc-0cd9d17bc352ea89.rlib" "/home/user1/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-musl/lib/liballoc-cdc59c0b9e33ea4d.rlib" "/home/user1/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-musl/lib/librustc_std_workspace_core-2c665cca95355961.rlib" "/home/user1/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-musl/lib/libcore-0f384d438fd9f6b3.rlib" "-Wl,--end-group" "/home/user1/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-musl/lib/libcompiler_builtins-10bfbfcd485da484.rlib" "-Wl,-Bdynamic" "-lstdc++" "-lpthread" "-lX11" "-lXext" "-lXinerama" "-lXcursor" "-lXrender" "-lXfixes" "-lXft" "-lfontconfig" "/home/user1/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-musl/lib/crtn.o"
  = note: /usr/bin/ld: /home/user1/code/fltk-rs/target/x86_64-unknown-linux-musl/release/deps/libfltk_sys-67e52d1c92b52bcd.rlib(Fl_Tree_Item.cxx.o): undefined reference to symbol '__printf_chk@@GLIBC_2.3.4'
          //lib/x86_64-linux-gnu/libc.so.6: error adding symbols: DSO missing from command line
          collect2: error: ld returned 1 exit status
          
error: aborting due to previous error
error: could not compile `fltk-rs`.
To learn more, run the command again with --verbose.

**Comment by MoAlyousef** [comment]
Well there are several issues.
The fltk-bundled flag since these are prebuilt packages for select platforms, and musl is not one of them. 
Second is that musl is a C library, not a C++ library, FLTK is C++ and needs the C++ standard library at least for placement new. For it to be done, the C++ standard needs to also be built against musl.
Third, adding musl support requires intrusive changes in the FLTK library itself, like defining _GNU_SOURCE (or similar defines) on gnu systems just to be able to get certain functions that FLTK uses such as strlcpy.
