### ISSUE TITLE
Failed to build on Windows 10 LTSB

### ISSUE THREAD

**Issue by ThisIsRex** [MoAlyousef/fltk-rs#264]
**Describe the bug**
I set `fltk = "^0.8"` in the dependency list and used an example code:

```
use fltk::{app::*, window::*};

fn main() {
    let app = App::default();
    let mut wind = Window::new(100, 100, 400, 300, "Hello from rust");
    wind.end();
    wind.show();
    app.run().unwrap();
}
```

**To Reproduce**
cargo run

**Expected behavior**
I expected the example will launch

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Version: LTSB

**Additional context**

```
   Compiling fltk-sys v0.8.0
   Compiling fltk-derive v0.8.0
error: failed to run custom build command for `fltk-sys v0.8.0`

Caused by:
  process didn't exit successfully: `O:\Rust\fltk_test\target\debug\build\fltk-sys-b3725011135e40ce\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=build.rs

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }', C:\Users\Admin\.cargo\registry\src\github.com-1ecc6299db9ec823\fltk-sys-0.8.0\build.rs:41:14
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by MoAlyousef** [comment]
It seems you're using the fltk-bundled flag, which requires curl and tar. These are normally available in the native tools command prompt (which you can get by typing "native" in the command prompt).
Otherwise, you can remove the fltk-bundled flag, but this will require cmake and a C++ compiler.

**Comment by ThisIsRex** [comment]
> 
> 
> It seems you're using the fltk-bundled flag, which requires curl and tar. These are normally available in the native tools command prompt (which you can get by typing "native" in the Start menu).
> Otherwise, you can remove the fltk-bundled flag, but this will require cmake and a C++ compiler.
I don't use `fltk-bundled` flag. Also I have cmake and c++ installed, a toolchain is msvc.
```
[dependencies]
fltk = "^0.8"
```

**Comment by MoAlyousef** [comment]
Strange. The unwrapping is happening in the build.rs line which uses curl. I've added expect messages to the build.rs several minutes ago. If it's not too much trouble, can you git clone the repo and run cargo build to see what error message you get?

**Comment by MoAlyousef** [comment]
Assuming this was somehow resolved?

**Comment by ThisIsRex** [comment]
> 
> 
> Strange. The panic is happening in the build.rs line which uses curl. I've added expect messages to the build.rs several minutes ago. If it's not too much trouble, can you git clone the repo and run cargo build to see what error message you get?

```
 --- stderr
  thread 'main' panicked at 'Git is needed to initialize the fltk repo!: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }', fltk-sys\build.rs:87:14
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
```

I have cloned using Github Desktop

**Comment by MoAlyousef** [comment]
Git needs to be added to your PATH.
