### ISSUE TITLE
[Doubt] Is there a channel to ask questions about the crate ?

### ISSUE THREAD

**Issue by Werner1201** [MoAlyousef/fltk-rs#267]
I'm here asking because I did not notice any places where I could ask questions about how to do certain things since reading the documentation and finding the right wording can be a pain. Is there a Discord or any other group chat where people can ask trivial questions?

**Comment by MoAlyousef** [comment]
Hi

There isn’t a dedicated channel for the crate unfortunately. 
But you can ask your questions here if you wish.

**Comment by Werner1201** [comment]
Ok, Thanks for the answer, I'll as the questions come up.

Em sáb, 15 de ago de 2020 13:29, Mohammed Alyousef <notifications@github.com>
escreveu:
