### ISSUE TITLE
[Doubt] Is there a way to make a clickable link ?

### ISSUE THREAD

**Issue by Werner1201** [MoAlyousef/fltk-rs#268]
I've been struggling in finding out how to make a clickable link. do I need to use an unstylished button?

**Comment by MoAlyousef** [comment]
fltk doesn’t really support hypertext links. It can be simulated using a frameless button:
´´´rust
let mut link = button::Button(/*params*/);
link.set_frame(FrameType::FlatBox);
link.clear_visible_focus();
link.set_label_color(Color::Blue);
link.set_callback(Box::new(move || {
    // callback code
}));
´´´

**Comment by Werner1201** [comment]
Ok, Thanks for the clarification. I'll close the issue when I get to my
computer

Em dom, 16 de ago de 2020 11:47, Mohammed Alyousef <notifications@github.com>
escreveu:
