### ISSUE TITLE
Menu example

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [MoAlyousef/fltk-rs#282]
I'd like to construct a menu for my app. I don't see any examples or docs for this, so I guess I'll have to figure it out from the code.

So my questions are:

- any pointers to help me (even on fltk with C/C++)?

- would you like a Menu example (in a PR) if I can figure it out?

**Comment by MoAlyousef** [comment]
Hello,

There's an example of a menu bar in the editor example here:
https://github.com/MoAlyousef/fltk-rs/blob/master/fltk/examples/editor.rs

It uses a SysMenuBar (to get MacOS menu bars), but you can use a MenuBar directly. The api is similiar for both. To add items you can use MenuBar::add() or MenuBar::add_emit(), the latter takes a sender and a message, while the former takes a boxed closure in place of both, both methods are part of the MenuExt trait:
https://docs.rs/fltk/0.8.5/fltk/prelude/trait.MenuExt.html

And yes I would love to have more examples in the repo :)
