### ISSUE TITLE
Add wrap_mode functions in TextDisplayExt

### ISSUE THREAD

**Issue by djarb** [MoAlyousef/fltk-rs#301]
**Is your feature request related to a problem? Please describe.**
Not being able to enable/disable word wrapping is keeping my project from being release-worthy.

**Describe the solution you'd like**
Add https://www.fltk.org/doc-1.3/classFl__Text__Display.html#ab9378d48b949f8fc7da04c6be4142c54 and related functions and enums to the bindings

**Comment by MoAlyousef** [comment]
Hi
I've added the DisplayExt::wrap_mode() method and the text::WrapMode enum. They're in master.
```rust
use fltk::*;
let mut editor = TextEditor::new(/* params */);
editor.wrap_mode(text::WrapMode::AtColumn, 10);
```
I've also added wrapped_row and wrapped_column, but these appear shaky to me, even in their docs!

**Comment by djarb** [comment]
Fast work. Thank you!
