### ISSUE TITLE
Threads example does not use app::lock() and app::unlock()

### ISSUE THREAD

**Issue by dheijl** [MoAlyousef/fltk-rs#304]
**Is your feature request related to a problem? Please describe.**

The threads example should use app::lock() in the main thread, and app::lock() an app::unlock() in the other thread that updates a widget (this is documented in FLTK).

Although it seems to work without in Windows, the GUI hangs solid after a couple of widget updates in Linux.
I did not test the example, but experienced it in a real app (https://github.com/dheijl/swyh-rs).

**Describe the solution you'd like**

Mentioning this somewhere and/or changing the threads example would be nice. 

But thanks for your excellent work on this, I really like it!

**Comment by MoAlyousef** [comment]
Hi. Thank you. Nice application by the way. 

As for locking, it should be carried out in the C++ wrapper's side. Every mutating action on a widget is surrounded by a LOCK macro (precedes the action by a lock() then follows the action by unlock and awake).
Also a lock is internally done before running the event loop, this enables the internal fltk lock before showing the windows or widgets. Also the message passing for callbacks depends on Fl::awake(void *) and Fl::thread_message() working correctly.
So normally things should work out with having to explicitly call app::lock() and app::unlock();

There could be missing LOCKs or bugs in the C++ wrapper, I would need to investigate it further.

**Comment by dheijl** [comment]
I can only say that according to the docs the main thread should call Fl::lock() only once, and all other threads should call Fl:lock() and Fl::unlock() when accessing widgets. On Windows it all worked without these calls, but on Linux without the locks the GUI hangs solid after just a couple of accesses by another thread. So if the problem is in the C++ wrapper you could still mention it as a work-around? Thanks for a quick response!

**Comment by MoAlyousef** [comment]
Sure, I'll add it to the FAQ and as a comment to the threads example.

**Comment by MoAlyousef** [comment]
Looking closer at the swyh-rs code, I see that you call app::wait_for, I have changed it to actually acquire a lock. FLTK uses recursive mutexes, so they can be called more than once, so long as the lock is reacquired by the widgets. I have removed all explicit calls to app::lock and app::unlock in swyh-rs, and it worked fine for me, even tho app::wait_for is called more than once.
The change is currently in master. You can add it using 
```toml
[dependencies]
fltk = { git = "https://github.com/moalyousef/fltk-rs" }
```
You can also point your cargo toml to your fork of cpal, which would make it easier for swyh-rs users to build from source without having to modify the Cargo.toml.
```toml
cpal = { git = "https://github.com/dheijl/cpal" }
```

**Comment by dheijl** [comment]
Thanks! I'll try your suggestions.

**Comment by dheijl** [comment]
I tried your suggestion (using git versions of fltk-rs and dheijl/cpal and removing the explicit locking calls), and it all works perfectly well now on Linux.

A big thank you! So I think we can close this issue?

**Comment by MoAlyousef** [comment]
Great. Yes I’ll close this issue.
