### ISSUE TITLE
recursion problem and invalid index in menubutton event handler

### ISSUE THREAD

**Issue by dheijl** [MoAlyousef/fltk-rs#311]
One user of swyh-rs (https://github.com/dheijl/swyh-rs) reports a problem in the menubutton event handler.
He can't choose a dropdown value: the index in the Push event is always invalid.
I can't reproduce this, and other users don't experience this problem either.

I inserted an eprintln! in the event handler printing out the event in an attempt to track it down, and this worked for me, but this user then always got "thread panicked while panicking" inside the event.

I then inserted a lock in the event handler preventing recursion (based on this post: https://groups.google.com/g/fltkgeneral/c/BjtPn6H0wec/m/WjELRgBYCQAJ) and this fixed the panic, but he still gets an invalid index (button.value()) in the PUSH event of the menubutton.

He has a very recent laptop, probably very fast. I tried this on 2 different windows versions and on Linux but I can't reproduce it.

Any ideas/hints? What do I miss? I can imagine that the event handler takes a bit long to execute because of the file io reading/writing the config value but still...

The event handler:
```rust
    let lock = Mutex::new(0);
    choose_audio_source_but.handle(Box::new(move |ev| {
        let mut recursion = lock.lock().unwrap();
        if *recursion > 0 {
            return false;
        }
        *recursion += 1;
        DEBUG!(eprintln!("Audio source dropdown event: {:?}", ev));
        match ev {
            Event::Push => {
                let mut config = Configuration::new().read_config();
                let i = butas_cc.value() as usize;
                if i >= devices.len() {
                    return true;
                }
                let name = devices[i as usize].name().unwrap();
                log(format!(
                    "*W*W*> Audio source changed to {}, restart required!!",
                    name
                )); // std::env::current_exe()
                config.sound_source = name;
                let _ = config.update_config();
                *recursion -= 1;
                true
            }
            _ => {
                *recursion -= 1;
                true
            }
        }
    }));
```

**Comment by dheijl** [comment]
Thank you very much for looking into this and pointing out the forward slash problem, it would probably have taken me ages to figure that out (if ever).
I'll implement a work-around later today by escaping/unescaping any slashes in the menu items.

**Comment by dheijl** [comment]
I encountered a similar issue with the vertical bar or pipe character '|' in the menubutton: it causes an item to split in two items.
So I had to "escape" that too. But apparently you can't escape | with a \, so I used the `` again as a replacement for |.

**Comment by MoAlyousef** [comment]
Thank you. I added a mention to the special characters for several widgets, the add_choice was missing any info.
