### ISSUE TITLE
Possibility of having Self reference in WidgetExt::draw

### ISSUE THREAD

**Issue by tslilc** [MoAlyousef/fltk-rs#314]
Thanks for this excellent library :)

**Is your feature request related to a problem? Please describe.**
I would like to use fltk-rs to implement a GUI for a board-game. This involves essentially creating my own widget for the board. Part of that is drawing graphical representation of the board. 

Unfortunately [WidgetExt::draw](https://docs.rs/fltk/0.9.7/fltk/prelude/trait.WidgetExt.html#tymethod.draw) accepts only a `Box<dyn FnMut()>` for the draw method, and so to find out things about the widget upon which i'm drawing (top-left corner, width, height, for correct offsets, scaling and clip among others) i need to go through a dance of using `Cell<RefCell<WidgetType>>` everywhere so that i can clone a reference to the widget and mutate it by setting its draw reference. 

This potentially incurs run-time errors do to overlapping borrows -- errors on my part certainly, but compile-time checking would be better. Moreover, it is frustrating to have to deal with the semantics of `Cell` and `RefCell` everywhere to obtain such a solution.

**Describe the solution you'd like**
I notice that you recently implemented `WidgetExt::set_callback2(&mut self, cb: Box<dyn FnMut(Self)>)`, an analogue of this for drawing would be perfect for my (and i imagine, many if not all) uses of draw:

    WidegtExt::draw2(&mut self, cb: Box<dyn FnMut(Self)>)

This would allow me to avoid the `Cell<RefCell<...>>` dance and write cleaner, more obviously correct code.

[TableExt::draw_cell](https://docs.rs/fltk/0.9.7/fltk/prelude/trait.TableExt.html#tymethod.draw_cell): `Box<dyn FnMut(TableContext, i32, i32, i32, i32, i32, i32)>` provides suitable information, and something simply including `Self` in `draw` would help immensely.

I presently do not need `&mut Self`, nor do i think that that would be very important.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by MoAlyousef** [comment]
Hi,
Thanks for your nice words. 
I've been working on a draw2 and handle2 methods. I've currently pushed my changes. I'll need to test the implementations first before publishing them into the next patch.

**Comment by MoAlyousef** [comment]
I've published a new version 0.10.0 with the current changes.

**Comment by tslilc** [comment]
Ah bravo! This is really fantastic, `draw2<F: FnMut(&mut Self) + 'static>(&mut self, cb: F)` is even nicer than i had been hoping for, no `Box`!

Excellent, thanks so much for your work.
