### ISSUE TITLE
Custom widget with data

### ISSUE THREAD

**Issue by GuzTech** [MoAlyousef/fltk-rs#320]
I want to implement a custom widget that has data, but I'm running into problems with the draw function requiring a `'static` lifetime. I've modified to the `custom_widget.rs` example like so:

```rust

struct FlatButton {
    wid: Widget,
    a: Vec<Option<i32>>,
}

impl FlatButton {
    pub fn new(x: i32, y: i32, w: i32, h: i32, label: &str) -> FlatButton {
        let mut x = FlatButton {
            wid: Widget::new(x, y, w, h, label),
            a: vec![Some(10), None, Some(20)],
        };
        x.draw();
        x.handle();
        x
    }

    // Overrides the draw function
    fn draw(&mut self) {
        let a = &self.a;

        self.wid.draw2(move |b| {
            draw::draw_box(
                FrameType::GtkDownBox,
                b.x(),
                b.y(),
                b.width(),
                b.height(),
                Color::from_u32(0xFFC300),
            );
            draw::set_draw_color(Color::Black);
            draw::draw_text_angled(-15, &b.label(), b.x() + 2, b.y() + 15);

            for v in a {
                if v.is_some() {
                    draw::draw_text(&format!("{}", v.unwrap()), b.x() + 2, b.y() + 30);
                }
            }
        });
    }
```

So the `a` field in `FlatButton` is a `Vec<Option<i32>>` and `Option` does not implement `Copy`. Of course I could implement it by hand, but I don't quite see why it shouldn't work like this. I cannot use `self` inside the closure, nor can I use `let a = &self.a;` because the compiler requires that everything inside the closure has `'static` lifetime which it cannot guarantee.

Is there a simple solution for this, or do I have to implement `Copy` for `Option`?

**Comment by MoAlyousef** [comment]
Hi
Widgets are effectively Arc<Mutex<fltk widget pointer>>. So if you need a stateful member to either enable cloning (here shallow copying), or to be able to consume a reference to the member inside a closure, it needs to be wrapped in an Rc<RefCell>> for single-threaded apps, or Arc<Mutex>> for multi-threaded apps.

For example, the previous code would look something like:
```rust
use fltk::{app, draw, frame::*, widget::*, window::*};
use std::ops::{Deref, DerefMut};
use std::cell::RefCell;
use std::rc::Rc;

struct FlatButton {
    wid: Widget,
    a: Rc<RefCell<Vec<Option<i32>>>>,
}

impl FlatButton {
    pub fn new(x: i32, y: i32, w: i32, h: i32, label: &str) -> FlatButton {
        let mut x = FlatButton {
            wid: Widget::new(x, y, w, h, label),
            a: Rc::from(RefCell::from(vec![Some(10), None, Some(20)])),
        };
        x.draw();
        x.handle();
        x
    }

    fn draw(&mut self) {
        let a = self.a.clone();

        self.wid.draw2(move |b| {
            draw::draw_box(
                FrameType::GtkDownBox,
                b.x(),
                b.y(),
                b.width(),
                b.height(),
                Color::from_u32(0xFFC300),
            );
            draw::set_draw_color(Color::Black);
            draw::draw_text_angled(-15, &b.label(), b.x() + 2, b.y() + 15);

            for v in &*a.borrow() {
                if v.is_some() {
                    draw::draw_text(&format!("{}", v.unwrap()), b.x() + 2, b.y() + 30);
                }
            }
        });
    }

    fn handle(&mut self) {
        let mut wid = self.wid.clone();
        self.wid.handle(move |ev| match ev {
            Event::Push => {
                wid.do_callback();
                true
            }
            _ => false,
        });
    }
}
```

**Comment by GuzTech** [comment]
Thanks for the quick answer!

I've got it to compile, but not work. The issue I had was that cloning `a` right before calling the `draw2` callback gave me an empty `Vec` since it wasn't populated when it was called. And since it was cloned, it doesn't matter that I update `self.a` later because the cloned `a` is a separate thing.

Now I also understand why you use a `Rc<RefCell<_>>` because I need to be able to reference the data at runtime. In my situation, I don't use an `i32` but a struct that cannot be copied, so I need references, and your solution should work just fine in my case :smile:
