### ISSUE TITLE
[BUG] make_resizable() has no effect after using ::default()

### ISSUE THREAD

**Issue by GuzTech** [MoAlyousef/fltk-rs#330]
**Describe the bug**
When creating a window using `::default()`, calling `make_resizable(true)` on that window does not make it resizable.

**To Reproduce**
The `counter` example is should create a resizable window, but it doesn't.

**Expected behavior**
The window should be resizable after calling `make_resizable(true)` on a window.

**Desktop (please complete the following information):**
 - OS: fully updated Arch Linux
 - fltk-rs version 0.10.4

**Additional context**
If a window is created with `::new()`, then `make_resizable(true)` works as expected.

**Comment by MoAlyousef** [comment]
Hi
I've pushed a change which I think fixes the issue. It's currently on master, but I'll publish a patch tonight.

**Comment by GuzTech** [comment]
I can confirm that it works correctly now :+1:
