### ISSUE TITLE
[BUG] SimpleTerminal Cursor Movement not functioning

### ISSUE THREAD

**Issue by mov-rax** [MoAlyousef/fltk-rs#358]
**Describe the bug**
The move_left(), move_right(), move_up(), and move_down() methods in SimpleTerminal are not functioning

**To Reproduce**
Try moving the terminal cursor left or right using any of the move methods.

**Expected behavior**
The cursor is expected to move.

**Screenshots**
Not applicable.

**Desktop (please complete the following information):**
 - OS: Arch Linux x86_64 (5.9.8-arch1-1)
 - Version: 0.10.10
 - Rust Version: 1.45.0
 - For build failures: `No build failure

**Additional context**
I am trying to make a SimpleTerminal widget's cursor move around the buffer, however, it is not working. The method itself returns Ok(()) but nothing is visible on the screen.

here is the function that I implemented in a project.
```rust
pub fn safe_move_cursor_left(&mut self){
        if self.term.insert_position() > self.root_query_pos{
            let result = match self.term.move_left() {
                Ok(()) => "SHOULD MOVE LEFT",
                Err(_) => "CANNOT MOVE LEFT"
            };
            println!("{}", result);
        }
    }
```

It prints out "SHOULD MOVE LEFT", but nothing is visible on the screen. I'm not sure what the problem is.

**Comment by MoAlyousef** [comment]
Hi
I can reproduce it also in C++.
It seems the Fl_Simple_Terminal is intended to work that way.
https://github.com/fltk/fltk/blob/5cb72ef065f53d8f8759a6b6cccd35a2f367f290/src/Fl_Simple_Terminal.cxx#L736

Unfortunately the only thing I can suggest is to implement the terminal using a TextDisplay. There's an example in the repo:
https://github.com/MoAlyousef/fltk-rs/blob/master/fltk/examples/terminal.rs

Appending will require something like: 
```rust
fn append(disp: &mut TextDisplay, txt: &str) {
    disp.buffer().unwrap().append(txt);
    disp.set_insert_position(disp.buffer().unwrap().length());
    disp.scroll(
        disp.count_lines(0, disp.buffer().unwrap().length(), true),
        0,
    );
}
``` 
to deal with auto scrolling the display widget.
Sorry

P.S. I've looked at the rcas application and it looks great. I'll try to implement it and open a pull request in a few days.

**Comment by mov-rax** [comment]
I see now. Much thanks!

For a while I was wondering if I would have to implement it in opengl or using the TextDisplay widget as you said above. If it could be implemented thru the library itself then that would be very helpful indeed :+1: . However, I do think that the documentation as it stands right now may mislead people (as it did to me) that the cursor is able to be moved.

**Comment by MoAlyousef** [comment]
Yes indeed. I’ll update the docs to reflect this limitation.
