### ISSUE TITLE
Unable to compile FLTK project

### ISSUE THREAD

**Issue by MikeeyBikeey** [MoAlyousef/fltk-rs#36]
I created a new project (`cargo new --vcs none fltk_app`) with `fltk = "0.2.12"` as a dependency but when I try to compile the project I get the following error message:
```
cargo run
    Updating crates.io index
  Downloaded fltk v0.2.12
  Downloaded fltk-derive v0.2.12
  Downloaded fltk-sys v0.2.12
   Compiling proc-macro2 v1.0.10
   Compiling unicode-xid v0.2.0
   Compiling cc v1.0.50
   Compiling syn v1.0.17
   Compiling cmake v0.1.42
   Compiling quote v1.0.3
   Compiling fltk-sys v0.2.12
error: failed to run custom build command for `fltk-sys v0.2.12`

Caused by:
  process didn't exit successfully: `C:\mike\rust\fltk_app\target\debug\build\fltk-sys-2b1c997f00afbb34\build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=build.rs
cargo:rerun-if-changed=cfltk/cfl.h
cargo:rerun-if-changed=cfltk/cfl_widget.h
cargo:rerun-if-changed=cfltk/cfl_group.h
cargo:rerun-if-changed=cfltk/cfl_window.h
cargo:rerun-if-changed=cfltk/cfl_button.h
cargo:rerun-if-changed=cfltk/cfl_box.h
cargo:rerun-if-changed=cfltk/cfl_menu.h
cargo:rerun-if-changed=cfltk/cfl_dialog.h
cargo:rerun-if-changed=cfltk/cfl_valuator.h
cargo:rerun-if-changed=cfltk/cfl_browser.h
cargo:rerun-if-changed=cfltk/cfl_misc.h
cargo:rerun-if-changed=cfltk/cfl_text.h
cargo:rerun-if-changed=cfltk/cfl_image.h
cargo:rerun-if-changed=cfltk/cfl_draw.h
cargo:rerun-if-changed=cfltk/global.h
cargo:rerun-if-changed=cfltk/cfl.cpp
cargo:rerun-if-changed=cfltk/cfl_widget.cpp
cargo:rerun-if-changed=cfltk/cfl_group.cpp
cargo:rerun-if-changed=cfltk/cfl_window.cpp
cargo:rerun-if-changed=cfltk/cfl_button.cpp
cargo:rerun-if-changed=cfltk/cfl_box.cpp
cargo:rerun-if-changed=cfltk/cfl_menu.cpp
cargo:rerun-if-changed=cfltk/cfl_dialog.cpp
cargo:rerun-if-changed=cfltk/cfl_valuator.cpp
cargo:rerun-if-changed=cfltk/cfl_browser.cpp
cargo:rerun-if-changed=cfltk/cfl_misc.cpp
cargo:rerun-if-changed=cfltk/cfl_text.cpp
cargo:rerun-if-changed=cfltk/cfl_image.cpp
cargo:rerun-if-changed=cfltk/cfl_draw.cpp
cargo:rerun-if-changed=cfltk/CMakeLists.txt
running: "cmake" "C:\\Users\\username\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\fltk-sys-0.2.12\\cfltk" "-G" "Visual Studio 16 2019" "-Thost=x64" "-Ax64" "-DOPTION_ABI_VERSION:STRING=10401" "-DOpenGL_GL_PREFERENCE=GLVND" "-DOPTION_BUILD_EXAMPLES=OFF" "-DOPTION_USE_THREADS=ON" "-DOPTION_LARGE_FILE=ON" "-DOPTION_USE_SYSTEM_ZLIB=OFF" "-DOPTION_USE_SYSTEM_LIBPNG=OFF" "-DOPTION_USE_SYSTEM_LIBJPEG=OFF" "-DOPTION_BUILD_HTML_DOCUMENTATION=OFF" "-DOPTION_BUILD_PDF_DOCUMENTATION=OFF" "-DCMAKE_INSTALL_PREFIX=C:\\mike\\rust\\fltk_app\\target\\debug\\build\\fltk-sys-3f72634ccbb802bf\\out" "-DCMAKE_C_FLAGS= -nologo -MD -Brepro" "-DCMAKE_C_FLAGS_RELEASE= -nologo -MD -Brepro" "-DCMAKE_CXX_FLAGS= -nologo -MD -Brepro" "-DCMAKE_CXX_FLAGS_RELEASE= -nologo -MD -Brepro" "-DCMAKE_BUILD_TYPE=RELEASE"
-- Configuring incomplete, errors occurred!
See also "C:/mike/rust/fltk_app/target/debug/build/fltk-sys-3f72634ccbb802bf/out/build/CMakeFiles/CMakeOutput.log".

--- stderr
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
CMake Error at CMakeLists.txt:2 (project):
  Generator

    Visual Studio 16 2019

  could not find any instance of Visual Studio.



thread 'main' panicked at '
command did not execute successfully, got: exit code: 1

build script failed, must exit now', C:\Users\username\.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.42\src\lib.rs:861:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
```
(I replaced my username with `username`)

**Comment by MoAlyousef** [comment]
Hello MikeeyBikeey
It seems cmake can't find your c++ compiler. Try running ```cargo run``` using the native tools command prompt*. It should appear once you start typing "native" in your start menu, it should have all PATH variables setup for native development.

* Normally you'd see 2 native tools prompts, one for x86 and one for x64, choose the one matching your rust toolchain.

**Comment by MikeeyBikeey** [comment]
It works!

Thanks for your time.

**Comment by MoAlyousef** [comment]
You’re welcome

**Comment by ekuiperemr** [comment]
Used Native shell and both CMake and GIT are in the path and are invokable on Windows 10. but I am not able to compile.

I get these errors:

C:\Users\fskhan\source\repos\FiveCentz\rustdesk>cargo build --release
   Compiling fltk-sys v1.1.18 (https://github.com/fltk-rs/fltk-rs#5cc968ba)
   Compiling which v3.1.1
   Compiling zstd v0.9.0+zstd.1.5.0
   Compiling libsodium-sys v0.2.7
   Compiling futures-executor v0.3.16
   Compiling hbb_common v0.1.0 (C:\Users\fskhan\source\repos\FiveCentz\rustdesk\libs\hbb_common)
   Compiling bindgen v0.59.1
error: could not find native static library `cfltk`, perhaps an -L flag is missing?

The following warnings were emitted during compilation:

warning: Could not find invokable CMake or Git, building using the fltk-bundled feature flag!
warning: If this is not desirable, please ensure CMake and Git are installed and in your PATH!

error: could not compile `fltk-sys` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed

THanks

**Comment by MoAlyousef** [comment]
What’s in your Cargo.toml? Or are you building the fltk-rs repo itself. What’s the architecture of your machine, 32bit or 64bit?

**Comment by travispaul** [comment]
Just want to add that I am was also seeing this on Windows, despite `cmake` and `git` both being installed and in my path:

```
warning: Could not find invokable CMake or Git, building using the fltk-bundled feature flag!
warning: If this is not desirable, please ensure CMake and Git are installed and in your PATH!
```

But this only occurred when running `cargo run --example xxx`, **before** running a successful `cargo build`

So if anyone else ends up here you might want to try running `cargo build` in a native tools prompt successfully, then try any examples.

That might be what @TopsDesk is running into?
