### ISSUE TITLE
Why does right_of(self, w, padding) use size of self instead of size of w

### ISSUE THREAD

**Issue by dheatovwil** [MoAlyousef/fltk-rs#365]
Given the following code:
```rust
let left = Button::default()
    .with_pos(0, 0)
    .with_size(80, 20)
    .with_label("left");

let right = Button::default()
    .with_size(30, 20)
    .right_of(&btn_left, 0)
    .with_label("right");
```
### Expected
Quoting the docs: `Positions the widget to the right of w, the size of w should be known`, `right` should be positioned **to the right of** `left`, roughly:
```
|        left        ||right|
```
Where `right.x() = left.x() + left.width()+padding`

### Actual
`right` is positioned based on its own size, yielding the result:
```
|       |right|     |
```
Where `right.x() = left.() + self.width()+padding`  
Excerpt from [fltk-drive/src/widget.rs#L833](https://github.com/MoAlyousef/fltk-rs/blob/master/fltk-derive/src/widget.rs#L833):
```rust
fn right_of<W: WidgetExt>(mut self, w: &W, padding: i32) -> Self {
    assert!(!w.was_deleted());
    assert!(!self.was_deleted());
    debug_assert!(self.width() != 0 && self.height() != 0, "right_of requires the size of the widget to be known!");
    self.resize(w.x() + self.width() + padding, w.y(), self.width(), self.height());
    self
}
```
In the function instead of using the size of `w`, the size of `self` is used.

**Comment by dheatovwil** [comment]
If my expected behavior is correct, I've created a PR with the fix: #366

**Comment by MoAlyousef** [comment]
Hi
You're right! It was a miscalculation.

**Comment by dheatovwil** [comment]
That's a very timely response =D. Aight, thanks for your hard work!

**Comment by MoAlyousef** [comment]
Thank you
