### ISSUE TITLE
FL_ALIGN_INSIDE  is needed

### ISSUE THREAD

**Issue by payallmoney** [MoAlyousef/fltk-rs#372]
FL_ALIGN_INSIDE  is needed
const Fl_Align FL_ALIGN_INSIDE = (Fl_Align)16

**Comment by MoAlyousef** [comment]
The issue is not clear. It's needed where?

**Comment by MoAlyousef** [comment]
It should be available in 0.10.15 tonight.

**Comment by payallmoney** [comment]
> It should be available in 0.10.15 tonight.
> 
> Edit: It's now available as
> Align::Inside

That's a very timely response .  thanks for your hard work!

**Comment by MoAlyousef** [comment]
Thank you
