### ISSUE TITLE
Adding combined ahortcuts à la CtrlShift, AltShift etc.

### ISSUE THREAD

**Issue by M4SSD35TRUCT10N** [MoAlyousef/fltk-rs#373]
**Is your feature request related to a problem? Please describe.**
I run into a problem when I wanted to open a new "window" with Ctrl+Shift+n. Then I realized that it isn't supported yet 'cause enums.rs' `pub enum shortcut` doesn't provide it.

**Describe the solution you'd like**
If possible add the common possible combinations of modifier keys to the enum of shortcut with the appropriate functioning - I don't see any dependencies so far, but I didn't dived into the source.

**Describe alternatives you've considered**
Currently Shift+n works for me but it's not the "standard" way things happen. Ctrl+n for new application window and Ctrl+Shift+n for a new window (or whatever e.g. new directory) for anything new beneath the level of the application itself.

**Comment by MoAlyousef** [comment]
Hi
I've added an implementation for Bitor for shortcuts. It should be possible to do ```Shortcut::Ctrl | Shortcut::Shift | 'n'````.
I haven't pushed it yet. It should be available in 0.10.15.

**Comment by M4SSD35TRUCT10N** [comment]
Hi @MoAlyousef ,

Thanks for the fast reply. I'm eager to try it out even, when my current app isn't more than a mockup. :-)

**Comment by MoAlyousef** [comment]
Great. It should be available now 👍

**Comment by M4SSD35TRUCT10N** [comment]
Works for me. Thanks for the fast implementation!
