### ISSUE TITLE
Subsystem "windows" for windows,  instead of console :D

### ISSUE THREAD

**Issue by Ar37-rs** [MoAlyousef/fltk-rs#378]
/// Just add this macro on top of the code
#![windows_subsystem = "windows"]

use fltk::{app::*, window::*};

fn main() {
    let app = App::default();
    let mut wind = Window::new(100, 100, 400, 300, "Hello from rust");
    wind.end();
    wind.show();
    app.run().unwrap();
}

fltk port is awesome anyway, thank you.

**Comment by MoAlyousef** [comment]
Thank you 👍 
I've added a note in the FAQ.
