### ISSUE TITLE
fltk-sys build fails on Windows with GNU Rust toolchain.

### ISSUE THREAD

**Issue by ZoomRmc** [MoAlyousef/fltk-rs#39]
Build fails on fltk-sys:
```
failed to run custom build command for `fltk-sys v0.2.16`
...
no valid generator found for GNU toolchain; MSYS or MinGW must be installed
```
Tried with different environments: Cygwin, MSYS2, mingw-w64 (which doesn't have cmake at all).

**Comment by MoAlyousef** [comment]
It seems to be an error message from the cmake crate:
https://github.com/alexcrichton/cmake-rs/blob/f43568caa7c770b50daa0527220b0ba8dda4a481/src/lib.rs#L424

It seems unable to find ```make```, which is strange since if I remember correctly, make comes preinstalled in MSYS2. I could be wrong though.

**Comment by ZoomRmc** [comment]
Thanks. I was confused by the error log line `running: "cmake" ...`, thus didn't even check what executable was missing (it's looking for `make` or `mingw32-make`, not `cmake`).
