### ISSUE TITLE
Selections in TableRow

### ISSUE THREAD

**Issue by ThiNei2l** [MoAlyousef/fltk-rs#396]
Hello there,

i hope i haven't completely missed something, but i can't find a way to _de_select rows.
In the original the functions `select_row` and `select_all_rows` take a bool flag to set or unset the selection.
Could you please add that or point out what i am missing?

Thanks

**Comment by MoAlyousef** [comment]
Hello
Yes this was an oversight in the bindings. I'll release a new version with the fix.

**Comment by MoAlyousef** [comment]
I have updated the master branch, where select_row and select_all_rows also take a TableRowSelectFlag enum. The values can be Deselect, Select and Toggle.
I'll publish in a bit

**Comment by ThiNei2l** [comment]
Wow, that was fast.
I already tried and it works.

Many thanks.
