### ISSUE TITLE
fluid like tool for UI design

### ISSUE THREAD

**Issue by diegoefe** [MoAlyousef/fltk-rs#411]
**Is your feature request related to a problem? Please describe.**
One of the best things about FLTK is the fluid ui designer which simplifies that matter a lot.

**Describe the solution you'd like**
A tool that parses de .fl like the one in the original C++ code but generates a corresponding .rs file.

**Describe alternatives you've considered**
I didn't consider any other alternatives so far, considering the existing fluid tool in the original project and the fact that this project is about a year old, and seems to work great so far

**Additional context**
In C++, using CMake, a automated task can be created to monitor every .fl file and generate the .h/.cpp pair (running fluid on the .fl file) when there are changes and force a recompile of the relevant sources

I apologize if some of this request is inaccurate because I come from a C++ background (and years of FLTK developement), just learning Rust from a couple of days and, thinking ahead, I know a tool of this kind will be a great bonus.

**Comment by MoAlyousef** [comment]
Hi

i think it’s reasonable to start with a subset of fluid’s functionality. The problem currently is that fluid itself is a bit too C++-centric. 
integration of fl files should be straightforward using a build.rs file and detecting changes to the fl files. 
It’ll also have to be in a separate project since by default it’ll be optional, and require its own set of dependencies. 

I’ll start a prototype soonish.

**Comment by dheijl** [comment]
Are you thinking of writing your own fluid implementation in Rust or rather of writing a .fl parser that generates Rust code from .fl files generated by fluid?

**Comment by MoAlyousef** [comment]
> Are you thinking of writing your own fluid implementation in Rust or rather of writing a .fl parser that generates Rust code from .fl files generated by fluid?

I would probably start with an .fl parser and see how that goes. I noticed the Fltkhs (Haskell) project does that as well.

**Comment by dheijl** [comment]
> I would probably start with an .fl parser and see how that goes. I noticed the Fltkhs (Haskell) project does that as well.

And [pyfltk](http://pyfltk.sourceforge.net/) as well, though the .fl parser flconvert is not really maintained it seems.

**Comment by MoAlyousef** [comment]
I've created the fl2rust repo
https://github.com/MoAlyousef/fl2rust
which is a preliminary and simplistic implementation. It might still be buggy.

I've also created a video tutorial on its usage:
https://www.youtube.com/watch?v=k_P0wG3-dNk

**Comment by diegoefe** [comment]
Excellent!

**Comment by MoAlyousef** [comment]
I've also published version 0.13 which should have better support for fl2rust. 
So I'll close this for now.
