### ISSUE TITLE
Implement callback_col and callback_row

### ISSUE THREAD

**Issue by JesperAxelsson** [MoAlyousef/fltk-rs#412]
I'm trying to implement sorting in a table and would like to be able to handle header clicks.
It would help a lot if you could implement both `callback_col` and `callback_row` [link](https://www.fltk.org/doc-1.3/classFl__Table.html#a5a34a561ff98dc0eba7a5bc866329343)

`callback_context` might be useful as well.

As far as I can tell handling header clicks is not possible without these functions, but I could be wrong.

Thanks for all your hard work!

**Comment by MoAlyousef** [comment]
Thank you. 

Sure, I’ll add them this evening.

**Comment by MoAlyousef** [comment]
Version 0.12.6 was released with the added methods.

**Comment by JesperAxelsson** [comment]
Thanks! You work fast :)
