### ISSUE TITLE
frame does not alter inside message passing / .wait()

### ISSUE THREAD

**Issue by ffleader1** [MoAlyousef/fltk-rs#415]
So I have this piece of code:

```
    let mut frame = Frame::new(440,row_y[4],320,240,"");

    w.make_resizable(true);
    w.end();
    w.show();

    let img= img_handler::gen_img();
    let (x,y)=img.dimensions();
    let mut rgb = fltk::image::RgbImage::new(&img.to_bytes(),x,y,3).unwrap();
    rgb.scale(320,240,false,true);
    println!("Drawing Image");
    frame.set_frame(UpBox);
    frame.set_image(Some(rgb));

    while myapp.wait() {
        match r.recv() {
            Some(msg) => match msg {
                Message::Debug => {
                },
            }
            None => {}
        }
        thread::sleep(time::Duration::from_millis(16));
    }

```

Which of course works and produce an image in place of an UpBox frame as expected:
![image](https://user-images.githubusercontent.com/15016720/103557332-a36ffe80-4e78-11eb-964e-c74956f9b409.png)

However, should I move the image creation piece of code inside the ```myapp.wait()```, it would not work. So the following code is a no-go:

```
    let mut frame = Frame::new(440,row_y[4],320,240,"");

    w.make_resizable(true);
    w.end();
    w.show();

    while myapp.wait() {
        match r.recv() {
            Some(msg) => match msg {
                Message::Debug => {
                      let img= img_handler::gen_img();
                      let (x,y)=img.dimensions();
                      let mut rgb = fltk::image::RgbImage::new(&img.to_bytes(),x,y,3).unwrap();
                      rgb.scale(320,240,false,true);
                      println!("Drawing Image");
                      frame.set_frame(UpBox);
                      frame.set_image(Some(rgb));
                },
            }
            None => {}
        }
        thread::sleep(time::Duration::from_millis(16));
    }

```
I know the "Debug" message got trigger because the program does print out "Drawing Image". However, neither the ```set_frame``` nor ```set_image``` works, and all I have is an empty area.
![image](https://user-images.githubusercontent.com/15016720/103557719-3b6de800-4e79-11eb-9994-ca652f12b357.png)
Is this some intended behavior of sort? 
I mean if so, how can I change the image based on user input? Thank you.

**Comment by MoAlyousef** [comment]
The lifetime of the image ends in that cycle. To get persistence, you can try using the ImageExt::draw method inside the widget's draw method, something like:
Notice you can also modify values passed into the draw closure by using an Rc Refcell for single-threaded code, and Arc mutext for multithreaded code.

```rust
use fltk::{app::*, button::*, frame::*, FrameType::*, image::*, window::*};
use std::rc::Rc;
use std::cell::RefCell;
use std::error::Error;

#[derive(Clone)]
enum Message {
    Debug(&'static str),
    Other,
}

fn main() {
    let myapp = App::default().with_scheme(Scheme::Gleam);
    let mut w = Window::new(100, 100, 400, 300, "Hello from rust");
    let mut frame = Frame::new(0, 0, 400, 200, "");
    let mut but = Button::new(169, 210, 80, 40, "Click me");
    w.end();
    w.show();

    let (s, r) = channel::<Message>();
    
    but.emit(s, Message::Debug("screenshots/charts.jpg"));
    
    let path = Rc::from(RefCell::from("".to_string()));
    let path_c = path.clone();

    frame.draw2(move |f| {
        f.set_frame(UpBox);
        let image = SharedImage::load(path_c.borrow().as_str());
        if let Ok(mut img) = image {
            img.draw(f.x(), f.y(), f.width(), f.height());
        }
    });
    
    
    while myapp.wait() {
        match r.recv() {
            Some(msg) => match msg {
                Message::Debug(p) => {
                      println!("Drawing Image");
                      *path.borrow_mut() = p.to_string();
                      frame.redraw(); 
                },
            }
            None => {}
        }
        std::thread::sleep(std::time::Duration::from_millis(16));
    }
}
```

**Comment by MoAlyousef** [comment]
A probably simpler solution which might work, you can try passing  app::redraw():

```rust
    while myapp.wait() {
        match r.recv() {
            Some(msg) => match msg {
                Message::Debug => {
                      let img= img_handler::gen_img();
                      let (x,y)=img.dimensions();
                      let mut rgb = fltk::image::RgbImage::new(&img.to_bytes(),x,y,3).unwrap();
                      rgb.scale(320,240,false,true);
                      println!("Drawing Image");
                      frame.set_frame(UpBox);
                      frame.set_image(Some(rgb));
                      app::redraw();
                },
            }
            None => {}
        }
        thread::sleep(time::Duration::from_millis(16));
    }
```

**Comment by ffleader1** [comment]
> A probably simpler solution which might work, you can try passing app::redraw() or frame.redraw():
> 
> ```rust
>     while myapp.wait() {
>         match r.recv() {
>             Some(msg) => match msg {
>                 Message::Debug => {
>                       let img= img_handler::gen_img();
>                       let (x,y)=img.dimensions();
>                       let mut rgb = fltk::image::RgbImage::new(&img.to_bytes(),x,y,3).unwrap();
>                       rgb.scale(320,240,false,true);
>                       println!("Drawing Image");
>                       frame.set_frame(UpBox);
>                       frame.set_image(Some(rgb));
>                       app::redraw();
>                 },
>             }
>             None => {}
>         }
>         thread::sleep(time::Duration::from_millis(16));
>     }
> ```

```frame.redraw()``` did the trick, and ```app::redraw()``` works also. Thank you. Though for curiosity, ```app::redraw()``` should be more computationally expensive right, as the whole app is redrawn?

**Comment by MoAlyousef** [comment]
> `frame.redraw()` did the trick, and `app::redraw()` works also. Thank you. Though for curiosity, `app::redraw()` should be more computationally expensive right, as the whole app is redrawn?

Indeed, app::redraw() is more expensive than a single widget's redraw call.

**Comment by ffleader1** [comment]
> > `frame.redraw()` did the trick, and `app::redraw()` works also. Thank you. Though for curiosity, `app::redraw()` should be more computationally expensive right, as the whole app is redrawn?
> 
> Indeed, app::redraw() is more expensive than a single widget's redraw call.

Though I do want to ask something related. I presume this ```redraw``` method works with other widgets. However, redrawing does not seem to remove the previous label.
![image](https://user-images.githubusercontent.com/15016720/103593313-2619ad80-4ebb-11eb-9707-2836c73d6947.png)
So I have an input with the label as shown on the top. I resize, set label and redraw it, and got the result as shown in the bottom. However, the residue of the previous label is still shown, which is most definitely not an intended behavior. 
Using ```app:redraw()`` works as intended but I was wondering if there is a more lenient method than redrawing the entire app interface.

**Comment by MoAlyousef** [comment]
You can also redraw the parent widget. Although app::redraw redraws everything it’s not so bad as long as you’re not doing it continuously. Other gui frameworks which are immediate mode guis like imgui basically redraw everything with each frame, that’s 60 frames per second.
