### ISSUE TITLE
FAQ suggestion

### ISSUE THREAD

**Issue by dheijl** [MoAlyousef/fltk-rs#431]
In the section "**Why do I get a console window whenever I start my GUI app?**" 

It's probably worth mentioning that one can also use
```rust
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]
```

to get the console window only in debug builds.
Before I discovered that I had to change this line every time I did a release build...

**Comment by M4SSD35TRUCT10N** [comment]
@dheijl This is exactly what I discovered today as I wanted this only for debugging. Yeah, definitely something that should be mentioned as it is very useful.

**Comment by MoAlyousef** [comment]
I didn't know that, that's really useful. Thanks for the suggestion!
I've gone ahead and added it to the faq.
