### ISSUE TITLE
UI not showing on Mac

### ISSUE THREAD

**Issue by alexxbb** [MoAlyousef/fltk-rs#432]
**Describe the bug**
Whenever I run any of the crate's examples on the command line, the UI won't show up until I press CTRL key on the terminal.

```
>> cargo run --example table
   Compiling fltk v0.13.1 (/private/tmp/fltk-rs/fltk)
    Finished dev [unoptimized + debuginfo] target(s) in 0.62s
     Running `target/debug/examples/table 
```
Only if I hit CTRL key just once, the UI pops up. Weird right? 

**Desktop (please complete the following information):**
 - OS: [MacOS BigSur]

Update:
I also found that it doesn't show up in MacOS Dock. So when I hit CTRL, the window itself shows up, but there's no icon appears in the Dock to indicate that some new app has started.

**Comment by MoAlyousef** [comment]
That's strange. What if you run the binary directly:
```./target/debug/examples/table```

**Comment by alexxbb** [comment]
I found this:
[https://abi-laboratory.pro/?view=changelog&l=fltk&v=1.3.4-1](https://abi-laboratory.pro/?view=changelog&l=fltk&v=1.3.4-1)

If you search for MacOS and Dock on that page, it mentions that it's been fixed.

**Comment by alexxbb** [comment]
> That's strange. What if you run the binary directly:
> `./target/debug/examples/table`
> or by double clicking the binary.

If I double click it first opens a terminal and then runs the gui in it. In this case the UI shows up, but its spawning a terminal... why is that I wonder?

**Comment by MoAlyousef** [comment]
> If I double click it first opens a terminal and then runs the gui in it. In this case the UI shows up, but its spawning a terminal... why is that I wonder?

That's normal behavior for executable binaries which aren't made into a MacOS app bundle, (for which you can use cargo-bundle https://github.com/burtonageo/cargo-bundle).

**Comment by alexxbb** [comment]
> > If I double click it first opens a terminal and then runs the gui in it. In this case the UI shows up, but its spawning a terminal... why is that I wonder?
> 
> That's normal behavior for executable binaries which aren't made into a MacOS app bundle, (for which you can use cargo-bundle https://github.com/burtonageo/cargo-bundle). Same for the lack of icon and dock.

What if I'm not going to run by double-clicking but rather directly from the command line. My other apps built with Gtk and Qt run directly from terminal. Is there anything can be done in this regards?

**Comment by MoAlyousef** [comment]
Does it work with:
```./target/debug/examples/table```

**Comment by alexxbb** [comment]
> Does it work with:
> ```./target/debug/examples/table```

Nope:
```
> cargo build --example table
> ./target/debug/examples/table
```
Is waiting for me to hit Ctrl 🙂 I'll play around with it a bit more. Interestingly that the link I posted above mentioned that this ( or similar?) Issue was resolved long time ago

**Comment by MoAlyousef** [comment]
Unfortunately I can't reproduce on BigSur. If you find out a fix or anything, I would be happy if you could report back.
![bigsur](https://user-images.githubusercontent.com/37966791/103954376-27660700-5155-11eb-8b9a-91bfef350a9c.gif)

**Comment by alexxbb** [comment]
Strange, thank you for taking a look, I'll make sure to update you if I find something.

**Comment by alexxbb** [comment]
I compiled the latest fltk (c++) from source and it ran as expected, while rust fltk didn't.... until I restarted my Mac! I don't know why, but this did the trick and now it's working well! ( Lesson: Macs need restart too once in a while 😄 ) 

Thanks!

**Comment by alexxbb** [comment]
I found the issue, thought this might help someone! 
**All this time I was launching the fltk app in the terminal from the /tmp folder** ( I had just git cloned repo fltk-rs into there) 

This folder is somehow special in MacOs (like everything in Mac) once I copied the examples to my Home folder - everything worked! God damn you apple :)
