### ISSUE TITLE
[BUG] Uneditable Float Input & Slider in Vector

### ISSUE THREAD

**Issue by ffleader1** [MoAlyousef/fltk-rs#454]
**Describe the bug**
I have several Float inputs and Sliders that sharing similarities so I decided to put them into a vector. However, only the odd ones are editable for some reason.

I declare them using the following code:
````
    let mut jul_inp_color_config_vec:Vec<FloatInput>=Vec::new();
    jul_inp_color_config_vec.push( FloatInput::new(286, row_y[8], 50, row_height, "From: "));
    jul_inp_color_config_vec.push( FloatInput::new(536, row_y[8], 50, row_height, "To: "));
    jul_inp_color_config_vec.push( FloatInput::new(286, row_y[9], 50, row_height, "From: "));
    jul_inp_color_config_vec.push( FloatInput::new(536, row_y[9], 50, row_height, "To: "));
    jul_inp_color_config_vec.push( FloatInput::new(286, row_y[10], 50, row_height, "From: "));
    jul_inp_color_config_vec.push( FloatInput::new(536, row_y[10], 50, row_height, "To: "));

    let mut jul_sli_color_config_vec:Vec<Slider>=Vec::new();
    jul_sli_color_config_vec.push( Slider::new(350, row_y[8], 120, row_height, ""));
    jul_sli_color_config_vec.push( Slider::new(600, row_y[8], 120, row_height, ""));
    jul_sli_color_config_vec.push( Slider::new(350, row_y[9], 120, row_height, ""));
    jul_sli_color_config_vec.push( Slider::new(600, row_y[9], 120, row_height, ""));
    jul_sli_color_config_vec.push( Slider::new(350, row_y[10], 120, row_height, ""));
    jul_sli_color_config_vec.push( Slider::new(600, row_y[10], 120, row_height, ""));
````

Only the odd ones can be edited (note the edit cursor in the screenshot) and only the odd sliders can be changed.
![image](https://user-images.githubusercontent.com/15016720/105454295-3a91d000-5c47-11eb-882f-b7d1a7103636.png)

The even inputs in the vector cannot be edited (show no edit cursor) nor can their corresponding slider be changed also.
![image](https://user-images.githubusercontent.com/15016720/105454415-6ca33200-5c47-11eb-8eec-8dc2ad1c72a3.png)

I am programming on Windows 10.

**Comment by ffleader1** [comment]
So I forgot to explain the boundary of the group, that is why only some part is editable.
I wonder if there is a way to sound boundaries in fltk.

**Comment by MoAlyousef** [comment]
You can add widgets to a Pack and you only have to define the coordinates of the pack. It’s like in the calculator example.
