### ISSUE TITLE
How can I debug Rust on Android

### ISSUE THREAD

**Issue by creasexul** [MoAlyousef/fltk-rs#459]
I'm trying to develop Android apps by Rust. But when I try to debug it, I can't find the direct way to touch this, only by command lines.
Is there any way more?

**Comment by MoAlyousef** [comment]
Hi
Unfortunately I currently don’t know of any other way. Android Studio doesn’t support Rust debugging.

**Comment by creasexul** [comment]
I'm try to debug with CLion.
But when I setup forwarding port and attach to CLion remote debugger, code in Java also be breaked.
I tried to use jdb to attach this progress, but failed.

**Comment by MoAlyousef** [comment]
Sorry I’m also unfamiliar with CLion. Did you try with gdb that comes with the Android ndk?

**Comment by creasexul** [comment]
Thanks a lot.
I try to use lldb to debug Rust and it works well.
Now I'm using gradle plugin from [rust-android-gradle](https://github.com/mozilla/rust-android-gradle).
Thank you for your advs.
