### ISSUE TITLE
[BUG] Add choice with forward slash error

### ISSUE THREAD

**Issue by ffleader1** [MoAlyousef/fltk-rs#468]
**Describe the bug**
This is quite a small bug, but it is pretty weird.
Adding a forward slash to choice string may result in a strange option
```
dragon_choice_start_1_vec.push(Choice::new(73, row_y[6+i], 100, row_height, &format!("{} Dragon is ", Ordinal(i+1).to_string())));
        dragon_choice_start_1_vec[i].add_choice("Above");
        dragon_choice_start_1_vec[i].add_choice("Under");
        dragon_choice_start_1_vec[i].add_choice("Opposite");
        dragon_choice_start_1_vec[i].add_choice("N/A");
        dragon_choice_start_1_vec[i].set_value(0);
```
Like this:
![image](https://user-images.githubusercontent.com/15016720/106409227-b3421a80-6405-11eb-8875-543f56c1d452.png)
So, yeah. Quite self-explanatory.
Tested with a few other special chars, and it seems back slash seem to have some issue as well.

**Comment by MoAlyousef** [comment]
Hi
It’s intended behavior and documented here:
https://github.com/MoAlyousef/fltk-rs/blob/b27157e37d1b1ab4bf537685b3c067cbeed14f42/fltk/src/prelude.rs#L601

You can escape special characters using the backslash `.add_choice("N\/A")`

**Comment by ffleader1** [comment]
> Hi
> It’s intended behavior and documented here:
> https://github.com/MoAlyousef/fltk-rs/blob/b27157e37d1b1ab4bf537685b3c067cbeed14f42/fltk/src/prelude.rs#L601
> 
> You can escape special characters using the backslash `.add_choice("N\/A")`

oh well
I feel stupid now.
By the way, is there any option to add an un-shown value.
Like: ```choice.add_choice("1"); choice.add_choice("2");choice.add_choice("3");choice.add_choice("4");```
But the choice "3" is not shown.
The reason for this is when I call ```choice.value()```, it would return and int. If I do not add the choice "3" then the choice "4" will have an int value of 3, which is undesirable. I want to add it, but not show it out.
Is it possible?

**Comment by MoAlyousef** [comment]
Yes. You can do: 
```rust
    choice.add_choice("1");
    choice.add_choice("2");
    choice.add_choice("3");
    choice.add_choice("4");
    if let Some(mut item) = choice.find_item("3") {
        item.hide();
    }
```

**Comment by ffleader1** [comment]
> Yes. You can do:
> 
> ```rust
>     choice.add_choice("1");
>     choice.add_choice("2");
>     choice.add_choice("3");
>     choice.add_choice("4");
>     if let Some(mut item) = choice.find_item("3") {
>         item.hide();
>     }
> ```

Nice. Thank you.
