### ISSUE TITLE
Event::Resize is never being sent

### ISSUE THREAD

**Issue by CaseyB** [MoAlyousef/fltk-rs#494]
I'm trying to detect when a window is resized but I'm never getting the Resize event. I've set the window to be resizable and I can drag it around but I'm not getting any events. I tried to just check the window size each time in the `app.wait()` loop but the loop stops running while I'm resizing the window so I don't see the size change until I stop. Also, I'm rendering in this loop so rendering stops when I'm resizing too.

**Comment by MoAlyousef** [comment]
Hi
The Resize event is a hack since FLTK doesn't actually emit them. So the only way to detect them is in the handle or handle2 methods.
```rust
    window.handle(|ev| match ev {
        Event::Resize => {
            println!("Resized");
            true
        },
        _ => false,
    });
```

**Comment by CaseyB** [comment]
Ahh, that's perfect. Thank you!
