### ISSUE TITLE
Painting example issue

### ISSUE THREAD

**Issue by asimaranov** [MoAlyousef/fltk-rs#495]
Paint example doesn't work on macos
I cloned the repo and run the paint example. It does not respond to clicking and dragging. Nothing but a white screen. Macos big sur
 ![image](https://user-images.githubusercontent.com/25568730/107270755-6640f280-6a5c-11eb-9d65-aef5a1861787.png)

**Comment by asimaranov** [comment]
![image](https://user-images.githubusercontent.com/25568730/107273534-3b589d80-6a60-11eb-9932-43f21326c10f.png)
Logs from uncommented lines

**Comment by MoAlyousef** [comment]
Thanks for the report. Unfortunately FLTK has issues with offscreen drawing on macos.

**Comment by MoAlyousef** [comment]
For specialized drawing, I would suggest using a specialized crate. Here is an example of using raqote in a painter like program:
https://github.com/MoAlyousef/fltk-rs-demos/tree/master/raqote

**Comment by asimaranov** [comment]
Thanks for your answer. I want to use the library as a backend for my eink reader gui framework so I can test gui on my pc. I need to draw geometric shapes, lines, dots etc. But its seems not to work too. What am I doing wrong?
![image](https://user-images.githubusercontent.com/25568730/107335051-86a69680-6ac8-11eb-828d-dd43c46bc8ce.png)
![image](https://user-images.githubusercontent.com/25568730/107335797-6deab080-6ac9-11eb-809a-edd95edc273d.png)

**Comment by MoAlyousef** [comment]
Cool project idea!
Draw calls should be in the draw method of the widget:
```rust
wind.draw(|| draw_rect_fill(args));
```

**Comment by MoAlyousef** [comment]
The paint example should be working now on macos.
