### ISSUE TITLE
[BUG] LabelType::Multi causes segmentation fault

### ISSUE THREAD

**Issue by crumblingstatue** [MoAlyousef/fltk-rs#519]
Setting the label type of a widget to LabelType::Multi causes segmentation fault.

Here is code to reproduce:
```Rust
use fltk::{app::*, window::*, frame::*};

fn main() {
	let app = App::default();
	let mut win = Window::default().with_size(400, 400);
	let mut f = Frame::default().with_label("hi").size_of(&win);
	f.set_label_type(LabelType::Multi);
	win.show();
	app.run().unwrap();
}
```

**Expected behavior**
I have no idea what Multi label type does, I was just experimenting.

**Meta info**
 - OS: Arch Linux x86_64
 - FLTK Version 0.14.5

**Comment by MoAlyousef** [comment]
I’ll have to check when I get home. 

Are the other label types also causing issues?
A multilabel supports an image and text at the same time.

**Comment by MoAlyousef** [comment]
I have disabled LabelType::Multi. To combine an image with text, one can override the WidgetBase::draw call or use set_align with TextOverImage or ImageBackdrop.
