### ISSUE TITLE
Is it possible to add a CallBackTrigger::Leave ?

### ISSUE THREAD

**Issue by dheijl** [MoAlyousef/fltk-rs#539]
Currently I have to handle `Counter `widget changes by using the `handle2`() method and testing for the `Leave `event, because I want to give the user the possibility to continue changing the counter with the arrows until the value is acceptable. `Change `does not work because it triggers the callback on every arrow press. 

It would be nice if I could set the `Leave` `CallBackTrigger `and use the `set_callback2`() method instead.

The only other `CallBackTrigger `that I see that I could use to get the same effect is `Enter `but I don't want to force the use of the keyboard.

**Comment by MoAlyousef** [comment]
Unfortunately there is no Leave trigger: 
https://github.com/fltk/fltk/blob/e19bfc0d8ff38672315f6500c441d3a716ff3aee/FL/Enumerations.H#L421

However, you can probably try the Event::Unfocus which might be more appropriate and should trigger with the Enter key as well. Also if you need to call a callback with multiple triggers that aren't available in the CallbackTrigger enum, then you can try the do_callback() method:
```rust
    ssdp_interval.set_trigger(fltk::enums::CallbackTrigger::EnterKey); // not really needed
    ssdp_interval.set_callback2(move |b| {
        let mut conf = CONFIG.write();
        if b.value() < 0.5 {
            b.set_value(0.5);
        }
        if (conf.ssdp_interval_mins - b.value()).abs() > 0.09 {
            conf.ssdp_interval_mins = b.value();
            log(format!(
                "*W*W*> ssdp interval changed to {} minutes, restart required!!",
                conf.ssdp_interval_mins
            ));
            let _ = conf.update_config();
            config_ch_flag.set(true);
            app::awake();
        }
    });
    ssdp_interval.handle2(move |b, ev| match ev {
        Event::Unfocus => {
            b.do_callback();
            true
        }
        _ => false,
    });
```

**Comment by dheijl** [comment]
Thanks, I didn't check FLTK, sorry...
