### ISSUE TITLE
WidgetExt for MenuItem?

### ISSUE THREAD

**Issue by wyhinton** [MoAlyousef/fltk-rs#542]
I think further customization of ```MenuItem``` would be a useful feature.  Could ```MenuItem``` impliment ```WidgetExt```? 

Particular use case I'm needing right now:
```
for  x in my_menu_bar.into_iter():
     x.set_frame(FrameType::FlatBox)
     x.set_color(Color::Dark3)
```

**Comment by MoAlyousef** [comment]
Hi

I'm afraid it's not possible. On the FLTK side, Fl_Menu_Item doesn't inherit from Fl_Widget, and thus doesn't provide a set_frame or set_color equivalents. 

The closest thing is to set these for the menu bar itself. The color would apply to all children and the frame type to all submenus.
