### ISSUE TITLE
Widget Damage

### ISSUE THREAD

**Issue by wyhinton** [MoAlyousef/fltk-rs#546]
FLTK's "damage" feature is pretty hard to get your head around, but seems for in important feature for more advanced drawing methods. A lot of fltk examples ([erco](http://seriss.com/people/erco/fltk/#DrawCoords), [FL_Scroll](https://github.com/fltk/fltk/blob/master/src/Fl_Scroll.cxx)), demonstrate using the damage Enums, ``` fltk::DAMAGE_VALUE, fltk::DAMAGE_PUSHED, fltk::DAMAGE_SCROLL, fltk::DAMAGE_OVERLAY,fltk::DAMAGE_HIGHLIGHT``` etc.  I can't say I feel like the original FLTK docs do a create job of explaining what widget damage is and how to use it, or why it's even called "damage". 

Will these enums be a future feature or are they not needed?

Any chance we could get an example of using damage for something like masking widgets as seen in FL_Scroll?

**Comment by MoAlyousef** [comment]
I can add it in the next patch as WidgetExt::damage_type. The bindings already have a WidgetExt::damage and set_damage, however non-zero values are considered true. Damage is used in FLTK to signal whether a widget should be redrawn. Finer-grained control might be important to minimize redraws.
