### ISSUE TITLE
RgbImage::draw() causing App crashes

### ISSUE THREAD

**Issue by wyhinton** [MoAlyousef/fltk-rs#550]
I'm not exactly sure what, but in upgrading to 15.8 something seems some kind of memory issue with ```RgbImage::draw()``` . ```draw::draw_image``` is working fine. I imagine the issue might have to do with the new ```ColorDepth enum```.

I'm not getting any specific error code, but just app crashes.  Switching all cases of RgbImage::draw() to draw::draw_image() (in both cases making sure I was using the correct ```ColorDepth``` fixed my problem. If the problem isn't readily clear after you look at the source doe I'll create a more detailed bug report.

On Windows 10.

**Comment by MoAlyousef** [comment]
Hi
Can you check with the current master. RgbImage::new now clones the data before sending to the C side, no leaks as well. If it works correctly I'll  yank versin 0.15.8 and publish a new one.

**Comment by wyhinton** [comment]
Seems to be working! I'll let you know if I run into any more issues.

**Comment by wyhinton** [comment]
Hey, sorry I didn't catch this completley the first time, but I'm with v 0.15.9 I'm having issues with drawing an RgbImage with L8 Depth. 

The large Image in the center of the frame should be the same image of the grey cup in the right side panel, just larger. 

```lang-rust

let img_width = self.grey_image.as_ref().width();
let img_height = self.grey_image.as_ref().height();
let bytes = self.grey_image.as_ref().unwrap().to_vec();
//self.grey_image is std::option::Option<image::ImageBuffer<image::Luma<u8>, std::vec::Vec<u8>>>
self.frame.draw2(move|widg|{
    let centered_x = (widg.parent().unwrap().x() + widg.parent().unwrap().width()/2) - (x/2) as i32;
    let centered_y = (widg.parent().unwrap().y() + widg.parent().unwrap().height()/2) - (y/2) as i32;
    match draw_image(&bytes, centered_x, centered_y, img_width as i32, img_height as i32, fltk::enums::ColorDepth::L8){
        Ok(img)=>img,
        Err(e)=>panic!("{}", e)
    };
});
```

This will intermitently lead the app to crash with error:
```
process didn't exit successfully: `target\release\MuTexAlpha.exe` (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)
```
The size of the image in question is 611x815. 

Windows 10, using 0.15.9
![image](https://user-images.githubusercontent.com/38958118/111022783-f7302400-83a2-11eb-90a6-6a40976a4b73.png)

**Comment by MoAlyousef** [comment]
I noticed this issue was reopened then reclosed, was it resolved?
I'm trying to replicate the problem on my side, but I can't even with arbitrary input for image data (which should panic on wrong image format).

**Comment by wyhinton** [comment]
Hey, thanks for checking it out! Reclosing was an accident. I'm going to do some more testing to see if I can narrow down the issue.

**Comment by MoAlyousef** [comment]
What's grey_image? Is it an fltk::image::RgbImage?
I'm not sure about the exit code, it seems to be a status access violation (window's equivalent of a segfault).

**Comment by wyhinton** [comment]
grey_image is is std::option::Option<image::ImageBuffer<image::Luma<u8>, std::vec::Vec<u8>>>, the standard output from [image::imageops::colorops::grayscale ](https://docs.rs/image/0.19.0/image/imageops/colorops/fn.grayscale.html)

**Comment by MoAlyousef** [comment]
Sorry missed the comment in the code snippet. 
I've tried to reproduce with:
```rust
use fltk::{app, draw, frame, prelude::*, window};
use image::io::Reader as ImageReader;
use std::error::Error;

fn main() -> Result<(), Box<dyn Error>> {
    let img = ImageReader::open("ex.jpg")?.decode()?;
    let img = image::imageops::colorops::grayscale(&img);
    let w = img.width();
    let h = img.height();
    let bytes = img.to_vec();

    let app = app::App::default();
    let mut wind = window::Window::default().with_size(600, 400);
    let mut frame = frame::Frame::default().size_of_parent();
    wind.end();
    wind.show();

    frame.draw2(move |widg| {
        match draw::draw_image(
            &bytes,
            widg.x(),
            widg.y(),
            w as i32,
            h as i32,
            ColorDepth::L8,
        ) {
            Ok(img) => img,
            Err(e) => panic!("{}", e),
        };
    });

    app.run()?;
    Ok(())
}
```
Also with just getting a luma image directly:
```rust
use fltk::{app, draw, frame, prelude::*, window};
use image::io::Reader as ImageReader;
use image::GenericImageView;
use std::error::Error;

fn main() -> Result<(), Box<dyn Error>> {
    let img = ImageReader::open("ex.jpg")?.decode()?;
    let (w, h) = img.dimensions();
    let bytes = img.to_luma8();

    let app = app::App::default();
    let mut wind = window::Window::default().with_size(600, 400);
    let mut frame = frame::Frame::default().size_of_parent();
    wind.end();
    wind.show();

    frame.draw2(move |widg| {
        match draw::draw_image(
            &bytes,
            widg.x(),
            widg.y(),
            w as i32,
            h as i32,
            ColorDepth::L8,
        ) {
            Ok(img) => img,
            Err(e) => panic!("{}", e),
        };
    });

    app.run()?;
    Ok(())
}
```
But both run fine.
The problem could be elsewhere. Are you deleting a widget somewhere or using any of the unsafe functions in fltk?

**Comment by wyhinton** [comment]
Ok so I haven't yet been able to re-create the issue entirely, but I created this repo, which gives me the same kind of image glitches I'm getting in my more complex application:

![image](https://user-images.githubusercontent.com/38958118/111949353-ee340680-8ab6-11eb-9c06-62ea65b8b159.png)

Could you test my example and see if you get the same results?

**Comment by MoAlyousef** [comment]
Sure I'll take a look at it

**Comment by wyhinton** [comment]
Yes this seems to have fixed the issue!
