### ISSUE TITLE
Input example

### ISSUE THREAD

**Issue by eternalmoon1234** [MoAlyousef/fltk-rs#558]
Hi there, this isn't an issue, but I was wondering how to use input::Input, in FLTK-rs. 

I checked the repository, your YouTube channel, and docs.rs, and didn't find anything, and just API docs. I'm trying to use input in my project, so could you give me an example of how input::Input works? Thanks.

**Comment by MoAlyousef** [comment]
Hello

All input (and output) widgets implement the [InputExt](https://docs.rs/fltk/0.15.10/fltk/prelude/trait.InputExt.html) trait. Probably the most important methods there are value() (return a &str) and and set_value(val: String).

```rust
    let mut input = input::Input::new(100, 10, 160, 40, "Enter name: ");
    input.set_value("your name");
    assert_eq!("your name", input.value());
```
The label is normally on the left, but can be changed using the set_align() method. The default callback trigger is CallbackTrigger::Release, however it can be changed using the WidgetExt::set_trigger() method like in the [temp_converter example](https://github.com/MoAlyousef/fltk-rs/blob/master/fltk/examples/temp_converter.rs).

**Comment by eternalmoon1234** [comment]
Thank you so much!
