### ISSUE TITLE
window icon question

### ISSUE THREAD

**Issue by dheijl** [MoAlyousef/fltk-rs#562]
Hi,

Is there any information on what format(s) the set_icon() function accepts?

I would like to add an icon to the window title bar, at least in Windows. I added the icon to the Windows exe with a winres build script.

**Comment by MoAlyousef** [comment]
Hello
set_icon() supports non-lazily rasterized image formats that are supported by fltk. Namely bmp, jpeg, png and rgb.
I'll add it to the docs.

**Comment by dheijl** [comment]
Thanks (again) for the quick response!

**Comment by dheijl** [comment]
Works like a charm, thanks!

![Knipsel](https://user-images.githubusercontent.com/2384545/111322923-b61d6580-8669-11eb-95d2-560ff4c880a1.PNG)

**Comment by MoAlyousef** [comment]
No problem. Looks really nice!
