### ISSUE TITLE
xft feature

### ISSUE THREAD

**Issue by wyhinton** [MoAlyousef/fltk-rs#566]
Would adding an ```enable-xft``` option for anti-aliased fonts be possible? According to [this ](https://www.fltk.org/articles.php?L374+I0+TFAQ+P1+Q) answer, this config enables AA for fonts. 

I've also read [here ](https://fltk.easysw.narkive.com/p6uhKzB5/how-to-disable-xft) that xft is enabled by default in FLTK  1.3, but can't seem to find anything in the FLTK docs backing that up. 

Anti-aliased fonts definitely give the UIs a more polished feel.

**Comment by MoAlyousef** [comment]
It's enabled by default and the build won't complete on missing libXft. However this is only applicable on Linux/BSD. On Windows and MacOS fltk uses WinGDI and Quartz respectively, should the text is also anti-aliased by default.

**Comment by wyhinton** [comment]
I see, maybe the chunkiness of my font is just an issue with the font itself. Thanks!
