### ISSUE TITLE
the @ character terminates a string when displayed with message_default

### ISSUE THREAD

**Issue by sdicker8** [MoAlyousef/fltk-rs#572]
**Describe the bug**
A string containing the @ character will not fully print with message_default.

**To Reproduce**
    let atsign = "scott@home".to_string();
    message_default(&atsign);

**Expected behavior**
I expected scott@home to be displayed. Only scott is displayed. I see that fltk uses @ symbols/commands to work with labels, but it doesn't seem like that should apply here.

**Desktop (please complete the following information):**
 - OS: Windows 10 x64,
 - Version: rust 1.50  fltk-rs 0.15.14

Thank you for fltk-rs Mohammed - this is a great asset for the rust community :)

**Comment by MoAlyousef** [comment]
Hi
Thank you for your kind words.
Yes FLTK treats the `@` sign as a special symbol. It can be escaped by preceding it with another `@`. `scott@@home`.

**Comment by sdicker8** [comment]
I agree with you then. I'm a bit surprised the lib authors made that decision. Thank you -
