### ISSUE TITLE
[BUG] Difference between compiling on Windows vs. Ubuntu?

### ISSUE THREAD

**Issue by ffleader1** [MoAlyousef/fltk-rs#575]
After trying to compile a program using FTLK Rust on both Windows and Ubuntu, I notice several difference.

The first one is GUI elements alignments.
Try the compiling [rust file crawler](https://github.com/bobahop/rust_filecrawler_fltk) on both Windows and Ubuntu one and the Ubuntu one looks like this:
![image](https://user-images.githubusercontent.com/15016720/111889270-edfe1300-89b1-11eb-8095-fb87a40bba99.png)

Second, the ubuntu one seems to be having some lag on having object get triggered. From a single source code, my code compiled on Windows and run file, but on Ubuntu, apparently there is some problem with either app.wait() or trigger. 
In my program, until I interact with a Menu::Choice widget, no other action will be triggered.
Link for screen recording of the problem:
https://youtu.be/Q8z9IeBQK9Y

**Comment by bobahop** [comment]
FYI, I only have Windows so I wasn't able to test rust file crawler on any other platform. Also, I used absolute positioning. At some point I want to go back and give relative positioning another try. Perhaps that would work better cross-platform. Finally, it's been a while since I've updated it to the latest version of fltk-rs.

**Comment by MoAlyousef** [comment]
I would say it’s a system font’s issue. For input and output widgets the default position of the label is Align::Left. The x and y coordinates take into account the position of the widget not of the widget’s label. Pssible solutions:
- to change the alignment of the label to be top left or just top.  
- to deploy a font with the application. 
- to add specific code for the target os changinh the font size. 
- to use WidgetExt::measure_label and reposition/resize the widget accordingly. 

As for the second issue and judging from the attached video, FLTK doesn’t detect changing an image of a widget as "damage", so it doesn’t redraw the widget automatically. I think the idea is to avoid unnecessary draws when initializing the application. I don’t think we should change that behavior. The solution is to manually call a widget’s redraw() method whenever its image changes. Or to provide a static variable which detects changes to an image and trigger a redraw in the event loop.

**Comment by MoAlyousef** [comment]
Regarding issue no. 1, I think it would be nice to add a function to set the default size of the font for the application. 
Currently this can be done by changing the global value of FL_NORMAL_SIZE:
```rust
    extern "C" {
        static mut FL_NORMAL_SIZE: i32;
    }
    unsafe {
        FL_NORMAL_SIZE = 12;
    }
```
Wrapping it in a safe (thread-safe) function would be handy. Devs won't need to set default font sizes for each widget.
The previous snippet gives the following for the rust_filecrawler gui.
![image](https://user-images.githubusercontent.com/37966791/111909064-cc159680-8a6c-11eb-9c2a-e79d7f849c72.png)

**Comment by ffleader1** [comment]
> Regarding issue no. 1, I think it would be nice to add a function to set the default size of the font for the application.
> Edit: I've add `app::set_font_size()` as a safe wrapper
> This gives the following appearance in the rust_filecrawler app (setting the font size to 12 on Ubuntu wsl):
> ![image](https://user-images.githubusercontent.com/37966791/111909064-cc159680-8a6c-11eb-9c2a-e79d7f849c72.png)

I did tried to test. So it seems version 0.16 works fine on the file crawler but completely murdered my program.
What is "Remove image conversion code" anyway, because it's definitely breaking.

**Comment by MoAlyousef** [comment]
It’s methods like into_jpeg, into_png and into_bmp. What’s the error you’re getting.

**Comment by ffleader1** [comment]
> It’s methods like into_jpeg, into_png and into_bmp. What’s the error you’re getting.
> 
> Edit: It was removed because it relied on system libjpeg and libpng headers (making the build process more prone to failure, and also risking ABI incompatibility with internal fltk code), it didn't take into account big endian for the bmp code. It assumed RGB888 which is not possible for some non-raster image types supported by fltk. It was also limited to only 3 formats. This can be done using a specialized crate like the image crate, which can do it better and for more image formats.

```
fn get_icon()-> fltk::image::RgbImage{
    let img = gen_icon(); //This function return a [dynamic image](https://docs.rs/image/0.23.14/image/enum.DynamicImage.html)
    let t_rgb =fltk::image::RgbImage::new(
        &img.to_bytes(), 220, 220, ColorDepth::Rgb8)
        .unwrap();
    t_rgb
}
```
This code runs fine on 0.15 but on 0.16, it just gave me a black/blank image.

**Comment by MoAlyousef** [comment]
Can you try with the latest fix. There was a problem in the RgbImage::new constructor which should be fixed.
