### ISSUE TITLE
[Help] A compilation error

### ISSUE THREAD

**Issue by stuartZhang** [MoAlyousef/fltk-rs#590]
**Describe the bug**

I executed the command "cargo build"

ERROR Logs:

  Submodule path 'cfltk/fltk': checked out '4657e988f7e351020876172218a5534e739bd18e'
  running: "cmake" "H:\\github_projects\\fltk-rs\\fltk-sys\\cfltk" "-G" "MSYS Makefiles" "-DOPTION_USE_SYSTEM_LIBPNG=OFF" "-DOPTION_USE_SYSTEM_LIBJPEG=OFF" "-DOPTION_USE_SYSTEM_ZLIB=OFF" "-DCFLTK_LINK_IMAGES=ON" "-DOpenGL_GL_PREFERENCE=GLVND" "-DOPTION_USE_GL=OFF" "-DCFLTK_USE_OPENGL=OFF" "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON" "-DFLTK_BUILD_EXAMPLES=OFF" "-DFLTK_BUILD_TEST=OFF" "-DOPTION_USE_THREADS=ON" "-DOPTION_LARGE_FILE=ON" "-DOPTION_BUILD_HTML_DOCUMENTATION=OFF" "-DOPTION_BUILD_PDF_DOCUMENTATION=OFF" "-DCMAKE_INSTALL_PREFIX=H:\\github_projects\\fltk-rs\\target\\debug\\build\\fltk-sys-00d7e89f8a38f049\\out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -m64" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -m64" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -m64" "-DCMAKE_BUILD_TYPE=Release"
  -- The C compiler identification is unknown
  -- The CXX compiler identification is unknown
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - failed
  -- Check for working C compiler: C:/MinGW/bin/gcc.exe
  -- Check for working C compiler: C:/MinGW/bin/gcc.exe - broken
  -- Configuring incomplete, errors occurred!
  See also "H:/github_projects/fltk-rs/target/debug/build/fltk-sys-00d7e89f8a38f049/out/build/CMakeFiles/CMakeOutput.log".
  See also "H:/github_projects/fltk-rs/target/debug/build/fltk-sys-00d7e89f8a38f049/out/build/CMakeFiles/CMakeError.log".

  --- stderr
  error: patch failed: src/CMakeLists.txt:300
  error: src/CMakeLists.txt: patch does not apply
  error: patch failed: src/Fl_win32.cxx:594
  error: src/Fl_win32.cxx: patch does not apply
  error: patch failed: src/drivers/Android/Fl_Android_System_Driver.H:25
  error: src/drivers/Android/Fl_Android_System_Driver.H: patch does not apply
  CMake Error at H:/github_projects/vcpkg/downloads/tools/cmake-3.19.2-windows/cmake-3.19.2-win32-x86/share/cmake-3.19/Modules/CMakeTestCCompiler.cmake:66 (message):
    The C compiler

      "C:/MinGW/bin/gcc.exe"

    is not able to compile a simple test program.

    It fails with the following output:

      Change Dir: H:/github_projects/fltk-rs/target/debug/build/fltk-sys-00d7e89f8a38f049/out/build/CMakeFiles/CMakeTmp
      
      Run Build Command(s):H:/github_projects/vcpkg/downloads/tools/msys2/b24ec64736bbaa92/usr/bin/make.exe cmTC_814b3/fast && /usr/bin/make  -f CMakeFiles/cmTC_814b3.dir/build.make CMakeFiles/cmTC_814b3.dir/build
      make[1]: 杩涘叆鐩綍鈥?cygdrive/h/github_projects/fltk-rs/target/debug/build/fltk-sys-00d7e89f8a38f049/out/build/CMakeFiles/CMakeTmp鈥?/bin/sh: /H/github_projects/vcpkg/downloads/tools/cmake-3.19.2-windows/cmake-3.19.2-win32-x86/bin/cmake.exe: No such file or directory
      make[1]: *** [CMakeFiles/cmTC_814b3.dir/build.make:84锛欳MakeFiles/cmTC_814b3.dir/testCCompiler.c.obj] 閿欒 127
      make[1]: 绂诲紑鐩綍鈥?cygdrive/h/github_projects/fltk-rs/target/debug/build/fltk-sys-00d7e89f8a38f049/out/build/CMakeFiles/CMakeTmp鈥?make: *** [Makefile:140锛歝mTC_814b3/fast] 閿欒 2

[CMakeOutput.log](https://github.com/MoAlyousef/fltk-rs/files/6212818/CMakeOutput.log)

[CMakeError.log](https://github.com/MoAlyousef/fltk-rs/files/6212820/CMakeError.log)

**Desktop (please complete the following information):**
 - OS: Windows 10 x64

**Comment by MoAlyousef** [comment]
You seem to be mixing toolchains together judging from the output of the error file.
What's the output of 
```
rustup toolchain list
```
Also can you build with
```
cargo build -vv
```
Also are you running the build from a cygwin shell, I see cygdrive?
