### ISSUE TITLE
GroupExt Additions

### ISSUE THREAD

**Issue by wyhinton** [MoAlyousef/fltk-rs#594]
Hello, 

Kindly requesting a couple functions for ```GroupExt```:

- clip_children()
- draw_child()
- draw_children()
- update_child()

I'm still trying to create my own custom scroll group and reading through the FLTK [source for FL_Scroll](https://github.com/fltk/fltk/blob/0c55cd1aca19b57a9b8837d1672ae260cfca4d78/src/Fl_Scroll.cxx) found a couple of these methods. 

Would be much appreciated!

**Comment by MoAlyousef** [comment]
Hi

I'll check it out.

**Comment by wyhinton** [comment]
Thanks!!
