### ISSUE TITLE
Clearing the Table widget

### ISSUE THREAD

**Issue by curldivergence** [MoAlyousef/fltk-rs#599]
Hello Mohammed,

First of all, thank you very much for the work you're doing, your library is fantastic :)
But unfortunately, I have a hard time using Table widget: I understand that it's just a simplistic view over user-provided data, but still do not get how it should be cleared on data change.
For instance, if I call redraw() on the table object from my "Update table" button callback, the font in the table just becomes bolder (as if some subpixel jitter was applied to the drawn text); this is how it looks in the beginning:
![image](https://user-images.githubusercontent.com/1927180/113516006-9ef2d900-9580-11eb-98a2-89bb791d74bb.png)
and this is the same table after several redraw() calls:
![image](https://user-images.githubusercontent.com/1927180/113516042-d1043b00-9580-11eb-8390-58ba9868c204.png)
A more serious issue I face is the fact that new data is being drawn over the old one despite the fact I call redraw() on update:
![image](https://user-images.githubusercontent.com/1927180/113516104-2b9d9700-9581-11eb-8a62-c1bd6796fa4b.png)
Only if I resize the table, it gets updated and behaves in the expected way:
![image](https://user-images.githubusercontent.com/1927180/113516130-512aa080-9581-11eb-97e8-f8dcb380e9fc.png)

I'm not really sure if I'm doing something wrong or this is a bug, so could you help me to sort this out, please?

Thank you!

**Comment by MoAlyousef** [comment]
Hello
Thank you.
FLTK's table's require a bit of boilerplate.
If you take the table example in the examples dir, and comment every line in the draw_data method except the draw_text part, you would similar artifacts. FLTK requires the explicit clipping, drawing of a filled rectangle then drawing text.

**Comment by curldivergence** [comment]
Ahh, I see, thanks. Just one more question then - why do we need the redraw() call at all? :) I can guess this clearing rectangle is supposed to be drawn even without manual redraw command?

**Comment by MoAlyousef** [comment]
You would only need to manually redraw when the data of the table changes, since fltk can’t detect that the data changed. 
otherwise, scrolling or resizing the table would do an automatic redraw.

**Comment by curldivergence** [comment]
But if resizing leads to automatic redraw, why does manual redraw only make things worse? :) Because apparently, fltk knows that it needs to clear the table, since it is clearing it on resize. So I would expect that manual redraw would have the same effect, but for some reason it does not :(
In the docs I've seen mentions that damage() and related calls only mark for redraw the parts of the widget itself, i.e. they skip "holes" in widgets if they are present. So probably, one should try to clear or redraw a higher-level widget, on which the Table is located? (In my case the table is located on a tab, so I could guess it would be the Group widget).

Thanks!

**Comment by MoAlyousef** [comment]
Hmm what I noticed was a similar artifact with automatic and manual redraws and the need redraw the cell's rect. 
However, yes, you can signal to the parent a redraw using set_damage/set_damage_type or directly redrawing the parent.

**Comment by curldivergence** [comment]
I've tried calling redraw() on parent (i.e. Group widget), but it led to the exact same result with 'bolder' text, just as if I called redraw() on the table itself.
I was still unsure about the solution with overpainting the text with a rectangle (once again, my concern was that everything becomes normal after a manual window resize, so it was clear that fltk *knows* what to do, just doesn't act on it for some reason), so I kept googling and finally found [this forum post](https://fltk.easysw.narkive.com/WV20fY7J/fltk-general-fl-table-row-and-widgets) (14 years old, lol) that says: 
> Do you find if you resize the window a little it redraws correctly?
>If so, try to tell the window() to redraw, eg. window()->redraw();

I've tried that, and it worked like a charm! Now I face none of the issues I have reported in this issue.
However, I still have no idea why it works, unfortunately - logically, my Group widget is a child of the Window, so why does redraw work on the topmost hierarchy level, but does not work on the lower ones?
Do you have any thoughts on this, by any chance? :)

**Comment by MoAlyousef** [comment]
I think I wasn't able to reproduce this since the table was a child of the window, however you were hitting this when the table is a child of another group widget. It sure is interesting, I have no explanation for it. But yes sure I'll add it to the docs and examples.

**Comment by curldivergence** [comment]
I see, thank you. I'll try to find the time to make a standalone minimal example and ask about it on fltk forums.
And for now I think we can close the issue, thank you very much for your help!
