### ISSUE TITLE
Add set_cursor(RGB, hotx, hoty) for WindowExt

### ISSUE THREAD

**Issue by wyhinton** [MoAlyousef/fltk-rs#613]
Hello,

Apparently FLTK has a means of adding custom cursors for a Window, as discussed in this [thread](https://groups.google.com/g/fltkgeneral/c/pQHA7XCRGcs). I was wondering if we could implement ```set_cursor(RGB, hotx, hoty)``` for WindowExt?

**Comment by MoAlyousef** [comment]
Hi
I've added it into the current master as WindowExt::set_cursor_image(). It will be published though in 1.0, due in a few days.
