### ISSUE TITLE
Editor Example - Saving Files

### ISSUE THREAD

**Issue by tataDan** [MoAlyousef/fltk-rs#629]
When I run the editor example using Debian 10 Linux everything works except for "Save" and "Save as". The save file dialog does appear.  I then enter a name and choose a directory, but when I click on the Save button a dialog appears with the message "Please specify a file!" and the file is not saved.

**Comment by eadf** [comment]
macOs too

**Comment by MoAlyousef** [comment]
Thanks for the heads up. I've modified the example in the master branch. The save_file method was checking if the path existed, which failed when inputting new files. Anyways, the whole lot of examples need rewriting and cleanup.

**Comment by tataDan** [comment]
Thanks for the quick response.

When using the modified code "Save" and "Save as" function as expected.
