### ISSUE TITLE
RgbImage::new use u32 instead of i32 for image width/height

### ISSUE THREAD

**Issue by wyhinton** [MoAlyousef/fltk-rs#634]
Thoughts on using u32 instead of i32 for setting the width/height of an RgbImage? When might you have a negative width or height for an image? 
```lang-rust
pub fn new(
    data: &[u8],
    w: u32,
    h: u32,
    depth: ColorDepth
) -> Result<RgbImage, FltkError>
```
instead of 
```lang-rust
pub fn new(
    data: &[u8],
    w: i32,
    h: i32,
    depth: ColorDepth
) -> Result<RgbImage, FltkError>
```

**Comment by MoAlyousef** [comment]
This was changed in 1.0, The reason is that such conversion code was already error-prone, u32::MAX can be larger than i32::MAX, so checking, and this applies to all code in the repo that took usize or u32 while FLTK took `int`. The debug_asserts were getting out of hand.
