### ISSUE TITLE
[BUG] no GUI shown and 100 % CPU since 1.04 

### ISSUE THREAD

**Issue by dheijl** [MoAlyousef/fltk-rs#643]
After recompiling with fltk-rs 1.04 swyh-rs no longer shows any GUI and the app (main thread) hangs in an endless CPU loop.

I suppose it has to do with the image changes in 1.04, because removing the following lines makes the problem go away:

```rust
        let icon_bytes = include_str!("../../assets/swyh-rs logo note-only 16x16.svg");
        if let Ok(icon) = SvgImage::from_data(icon_bytes) {
            wind.set_icon(Some(icon));
        }
```

**Comment by MoAlyousef** [comment]
Yeah I was able to reproduce. It seems FLTK stores an icon array (including the system default icon), so memory management there is a bit complex (i.e. I'll need to look closely into the implementation). I've reverted the changes just for WindowExt::set_icon, the other methods seem to function correctly. 

Can you try with the git repo as a dependency:
```toml
[dependencies]
fltk = { version = "1.0.5", git = "https://github.com/moalyousef/fltk-rs" }
```

**Comment by dheijl** [comment]
Yes, that seems to fix it, thanks.
