### ISSUE TITLE
Add bindings for more screen functions

### ISSUE THREAD

**Issue by wyhinton** [MoAlyousef/fltk-rs#651]
Hello! Thanks for your continued and always excellent work on this project. 

I was wondering if we might add bindings for these FLTK [Screen Functions](https://www.fltk.org/doc-1.3/group__fl__screen.html)

- ```Fl::screen_xywh()```
- ```Fl::screen_h()```
- ```Fl::screen_w()```
- ```Fl::screen_x()```
- ```Fl::screen_y()```
- ```Fl::screen_work_area()```

**Comment by MoAlyousef** [comment]
Thanks :)
Sure. Some can already be aquired via app::screen_size() which gives the width and height of the current screen.

**Comment by wyhinton** [comment]
Is the "current screen" the one that the mouse is located on?

**Comment by MoAlyousef** [comment]
I think it’s OS dependent, not sure about Windows, but screen 0 is the main screen and other screen can be explicitly toggled using some the display manager, or they automatically appear on extra monitors.

**Comment by MoAlyousef** [comment]
Added in 1.0.7
