### ISSUE TITLE
Is custom event supported?

### ISSUE THREAD

**Issue by super119** [MoAlyousef/fltk-rs#66]
I think custom event might be useful in a multi-thread environment. For example we have a few threads which do some heavy loading works and they'd like to inform the progress to the main thread. If fltk-rs supports custom events, that could be done by sending a custom event to main thread, then the main thread can update the widgets accordingly.

After some googling it seems that fltk has a function named "Fl::add_handler()" which can do that. Is this supported in fltk-rs?

**Comment by MoAlyousef** [comment]
Not yet. I’m contemplating adding it in a safe way. All my attempts would lead to a segfault if the application isn’t ready to handle events. I’ll update this issue when I figure out a solution.

**Comment by MoAlyousef** [comment]
I have added the add_handler function in the app module. Notice that like in C++, this function takes a non-capturing closure (no void *data field). 
I've also added app::awake, app::thread_msg and App::wait. 

This is a small example:
```rust
#[derive(Debug, Copy, Clone)]
pub enum Message {
    Increment,
    Decrement,
}

fn inc_frame(frame: &mut Frame, val: &mut i32) {
    *val = *val + 1;
    frame.set_label(&val.to_string());
}

fn main() {
    let app = App::default();
    let mut wind = Window::new(100, 100, 400, 300, "Hello from rust");
    let mut frame = Frame::new(0, 0, 400, 300, "");
    let mut val = 0;
    wind.show();
    std::thread::spawn(move || loop {
        std::thread::sleep(std::time::Duration::from_millis(1000));
        awake_msg(Message::Increment);
    });
    while app.wait() {
        let msg = thread_msg::<Message>();
        match msg {
            Some(Message::Increment) => inc_frame(&mut frame, &mut val),
            _ => (),
        }
    }
}
```
For the moment this still needs some better type checks. And it can't accept data-carrying enums due to layout issues with FFI.

**Comment by MoAlyousef** [comment]
Things also appear to work with channels:
```rust
#[derive(Debug, Copy, Clone)]
pub enum Message {
    Increment(i32),
    Decrement(i32),
}

fn inc_frame(frame: &mut Frame, val: &mut i32, step: i32) {
    *val = *val + step;
    frame.set_label(&val.to_string());
}

fn main() {
    let app = App::default();
    let mut wind = Window::new(100, 100, 400, 300, "Hello from rust");
    let mut frame = Frame::new(0, 0, 400, 300, "0");
    wind.end();
    wind.show();
    let (s, r) = std::sync::mpsc::channel::<Message>();
    std::thread::spawn(move || loop {
        std::thread::sleep(std::time::Duration::from_millis(1000));
        s.send(Message::Increment(2)).unwrap();
    });
    let mut val = 0;
    while app.wait() {
        match r.recv().unwrap() {
            Message::Increment(step) => inc_frame(&mut frame, &mut val, step),
            _ => (),
        }
    }
}
```

**Comment by super119** [comment]
This is cool! I'll give it a try. Thanks MoAlyousef.

**Comment by super119** [comment]
> Things also appear to work with mpsc channels:
> 
> ```rust
> #[derive(Debug, Copy, Clone)]
> pub enum Message {
>     Increment(i32),
>     Decrement(i32),
> }
> 
> fn inc_frame(frame: &mut Frame, val: &mut i32, step: i32) {
>     *val = *val + step;
>     frame.set_label(&val.to_string());
> }
> 
> fn main() {
>     let app = App::default();
>     let mut wind = Window::new(100, 100, 400, 300, "Hello from rust");
>     let mut frame = Frame::new(0, 0, 400, 300, "0");
>     wind.end();
>     wind.show();
>     let (s, r) = std::sync::mpsc::channel::<Message>();
>     std::thread::spawn(move || loop {
>         std::thread::sleep(std::time::Duration::from_millis(1000));
>         s.send(Message::Increment(2)).unwrap();
>     });
>     let mut val = 0;
>     while app.wait() {
>         match r.recv().unwrap() {
>             Message::Increment(step) => inc_frame(&mut frame, &mut val, step),
>             _ => (),
>         }
>     }
> }
> ```

Verified + 1
