### ISSUE TITLE
Pleased add timeout support

### ISSUE THREAD

**Issue by brmmm3** [MoAlyousef/fltk-rs#85]
Pleased add Support for functions: add_timeout, repeat_timeout and remove_timeout.

**Comment by MoAlyousef** [comment]
Hi
I have added these methods in the app module. It's currently in the master branch. I've also added an example which mimics the example in the original FLTK docs:
```rust
use fltk::*;
use fltk::prelude::*;

fn callback() {
    println!("TICK");
    app::repeat_timeout(1.0, Box::new(callback));
}

fn main() {
    let app = app::App::default();
    let mut wind = window::Window::new(100, 100, 400, 300, "");
    app::add_timeout(1.0, Box::new(callback));
    wind.end();
    wind.show();
    app.run().unwrap();
}
```

**Comment by brmmm3** [comment]
Many thanks for the very quick improvement!
