### ISSUE TITLE
Segmentation fault in save prompt

### ISSUE THREAD

**Issue by jlwoodwa** [MoAlyousef/fltk-rs#86]
When running the editor example and choosing "Save" or "Save as", the app crashes and "Segmentation fault" is printed in the terminal. (I am running Linux.)

Testing:
* This occurs regardless of theme.
* Valgrind shows that the error is an invalid read occurring while png data is being processed by GTK. (This is shown whether or not Gtk is the chosen theme.) Full Valgrind log: [valgrind.txt](https://github.com/MoAlyousef/fltk-rs/files/4605305/valgrind.txt)

**Comment by jlwoodwa** [comment]
It doesn't seem to be an issue with fltk itself; [this C++ example](https://github.com/IngwiePhoenix/FLTK/blob/master/examples/nativefilechooser-simple-app.cxx) runs fine.

**Comment by MoAlyousef** [comment]
Hi
I'm gonna need more information since I can't reproduce the issue on my Ubuntu 18.04.
What distro?
How did you build the editor example?
Were you using any flags, features?
How was the C++ example built?

**Comment by MoAlyousef** [comment]
After some digging, it seems related to this issue:
[Fl_Native_File_Chooser() crash with FLTK 1.4](https://groups.google.com/forum/#!msg/fltkgeneral/zYbxVV7IOY0/dM_lPM_nBQAJ)

You can try using the system-libpng feature:
```toml
[dependencies]
fltk = { git=https://github.com/MoAlyousef/fltk-rs, features=["system-libpng"] }
```
Which would use the local installation of libpng.
