### ISSUE TITLE
with_align

### ISSUE THREAD

**Issue by brmmm3** [MoAlyousef/fltk-rs#97]
Please add `with_align`.

**Comment by MoAlyousef** [comment]
Do you mean in the builder pattern?

**Comment by brmmm3** [comment]
Yes

**Comment by MoAlyousef** [comment]
I have added it to the master branch. However, since I’m working a tree widgets currently, I’ll publish it to a new minor version when the trees and tree items are perfed.

**Comment by MoAlyousef** [comment]
Published to 0.4.5

**Comment by brmmm3** [comment]
Thank you very much for the quick Implementation!

Mohammed Alyousef <notifications@github.com> schrieb am Di., 19. Mai 2020,
00:36:
